/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class _PostgisJoinSelectivity :
    AbstractRoutine<Double>("_postgis_join_selectivity", Public.PUBLIC, DSL.comment(""), SQLDataType.DOUBLE) {
    companion object {
        /**
         * The parameter
         * <code>public._postgis_join_selectivity.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Double?> = Internal.createParameter("RETURN_VALUE", SQLDataType.DOUBLE, false, false)

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val _1: Parameter<Any?> =
            Internal.createParameter(
                "_1",
                DefaultDataType.getDefaultDataType("\"pg_catalog\".\"regclass\""),
                false,
                true
            )

        /**
         * The parameter <code>public._postgis_join_selectivity._2</code>.
         */
        val _2: Parameter<String?> = Internal.createParameter("_2", SQLDataType.CLOB, false, true)

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val _3: Parameter<Any?> =
            Internal.createParameter(
                "_3",
                DefaultDataType.getDefaultDataType("\"pg_catalog\".\"regclass\""),
                false,
                true
            )

        /**
         * The parameter <code>public._postgis_join_selectivity._4</code>.
         */
        val _4: Parameter<String?> = Internal.createParameter("_4", SQLDataType.CLOB, false, true)

        /**
         * The parameter <code>public._postgis_join_selectivity._5</code>.
         */
        val _5: Parameter<String?> =
            Internal.createParameter(
                "_5",
                SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("'2'::text"), SQLDataType.CLOB)),
                true,
                true
            )
    }

    init {
        returnParameter = _PostgisJoinSelectivity.RETURN_VALUE
        addInParameter(_PostgisJoinSelectivity._1)
        addInParameter(_PostgisJoinSelectivity._2)
        addInParameter(_PostgisJoinSelectivity._3)
        addInParameter(_PostgisJoinSelectivity._4)
        addInParameter(_PostgisJoinSelectivity._5)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Any?): Unit = setValue(_PostgisJoinSelectivity._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Any?>) {
        setField(_PostgisJoinSelectivity._1, field)
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    fun set__2(value: String?): Unit = setValue(_PostgisJoinSelectivity._2, value)

    /**
     * Set the <code>_2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__2(field: Field<String?>) {
        setField(_PostgisJoinSelectivity._2, field)
    }

    /**
     * Set the <code>_3</code> parameter IN value to the routine
     */
    fun set__3(value: Any?): Unit = setValue(_PostgisJoinSelectivity._3, value)

    /**
     * Set the <code>_3</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__3(field: Field<Any?>) {
        setField(_PostgisJoinSelectivity._3, field)
    }

    /**
     * Set the <code>_4</code> parameter IN value to the routine
     */
    fun set__4(value: String?): Unit = setValue(_PostgisJoinSelectivity._4, value)

    /**
     * Set the <code>_4</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__4(field: Field<String?>) {
        setField(_PostgisJoinSelectivity._4, field)
    }

    /**
     * Set the <code>_5</code> parameter IN value to the routine
     */
    fun set__5(value: String?): Unit = setValue(_PostgisJoinSelectivity._5, value)

    /**
     * Set the <code>_5</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__5(field: Field<String?>) {
        setField(_PostgisJoinSelectivity._5, field)
    }
}
