/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

@Deprecated(
    message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
)
@Suppress("warnings")
open class _PostgisIndexExtent :
    AbstractRoutine<Any>(
        "_postgis_index_extent",
        Public.PUBLIC,
        DSL.comment(""),
        DefaultDataType.getDefaultDataType("\"public\".\"box2d\"")
    ) {
    companion object {
        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val RETURN_VALUE: Parameter<Any?> =
            Internal.createParameter(
                "RETURN_VALUE",
                DefaultDataType.getDefaultDataType("\"public\".\"box2d\""),
                false,
                false
            )

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val TBL: Parameter<Any?> =
            Internal.createParameter(
                "tbl",
                DefaultDataType.getDefaultDataType("\"pg_catalog\".\"regclass\""),
                false,
                false
            )

        /**
         * The parameter <code>public._postgis_index_extent.col</code>.
         */
        val COL: Parameter<String?> = Internal.createParameter("col", SQLDataType.CLOB, false, false)
    }

    init {
        returnParameter = _PostgisIndexExtent.RETURN_VALUE
        addInParameter(_PostgisIndexExtent.TBL)
        addInParameter(_PostgisIndexExtent.COL)
    }

    /**
     * Set the <code>tbl</code> parameter IN value to the routine
     */
    fun setTbl(value: Any?): Unit = setValue(_PostgisIndexExtent.TBL, value)

    /**
     * Set the <code>tbl</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setTbl(field: Field<Any?>) {
        setField(_PostgisIndexExtent.TBL, field)
    }

    /**
     * Set the <code>col</code> parameter IN value to the routine
     */
    fun setCol(value: String?): Unit = setValue(_PostgisIndexExtent.COL, value)

    /**
     * Set the <code>col</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setCol(field: Field<String?>) {
        setField(_PostgisIndexExtent.COL, field)
    }
}
