/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class _StDfullywithin : AbstractRoutine<Boolean>("_st_dfullywithin", Public.PUBLIC, DSL.comment(""), SQLDataType.BOOLEAN) {
    companion object {
        /**
         * The parameter <code>public._st_dfullywithin.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Boolean?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BOOLEAN, false, false)

        /**
         * The parameter <code>public._st_dfullywithin.geom1</code>.
         */
        val GEOM1: Parameter<Geometry?> = Internal.createParameter("geom1", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public._st_dfullywithin.geom2</code>.
         */
        val GEOM2: Parameter<Geometry?> = Internal.createParameter("geom2", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public._st_dfullywithin._3</code>.
         */
        val _3: Parameter<Double?> = Internal.createParameter("_3", SQLDataType.DOUBLE, false, true)
    }

    init {
        returnParameter = _StDfullywithin.RETURN_VALUE
        addInParameter(_StDfullywithin.GEOM1)
        addInParameter(_StDfullywithin.GEOM2)
        addInParameter(_StDfullywithin._3)
    }

    /**
     * Set the <code>geom1</code> parameter IN value to the routine
     */
    fun setGeom1(value: Geometry?): Unit = setValue(_StDfullywithin.GEOM1, value)

    /**
     * Set the <code>geom1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom1(field: Field<Geometry?>) {
        setField(_StDfullywithin.GEOM1, field)
    }

    /**
     * Set the <code>geom2</code> parameter IN value to the routine
     */
    fun setGeom2(value: Geometry?): Unit = setValue(_StDfullywithin.GEOM2, value)

    /**
     * Set the <code>geom2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom2(field: Field<Geometry?>) {
        setField(_StDfullywithin.GEOM2, field)
    }

    /**
     * Set the <code>_3</code> parameter IN value to the routine
     */
    fun set__3(value: Double?): Unit = setValue(_StDfullywithin._3, value)

    /**
     * Set the <code>_3</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__3(field: Field<Double?>) {
        setField(_StDfullywithin._3, field)
    }
}
