/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Addgeometrycolumn2 : AbstractRoutine<String>("addgeometrycolumn", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter <code>public.addgeometrycolumn.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        /**
         * The parameter <code>public.addgeometrycolumn.schema_name</code>.
         */
        val SCHEMA_NAME: Parameter<String?> = Internal.createParameter("schema_name", SQLDataType.VARCHAR, false, false)

        /**
         * The parameter <code>public.addgeometrycolumn.table_name</code>.
         */
        val TABLE_NAME: Parameter<String?> = Internal.createParameter("table_name", SQLDataType.VARCHAR, false, false)

        /**
         * The parameter <code>public.addgeometrycolumn.column_name</code>.
         */
        val COLUMN_NAME: Parameter<String?> = Internal.createParameter("column_name", SQLDataType.VARCHAR, false, false)

        /**
         * The parameter <code>public.addgeometrycolumn.new_srid</code>.
         */
        val NEW_SRID: Parameter<Int?> = Internal.createParameter("new_srid", SQLDataType.INTEGER, false, false)

        /**
         * The parameter <code>public.addgeometrycolumn.new_type</code>.
         */
        val NEW_TYPE: Parameter<String?> = Internal.createParameter("new_type", SQLDataType.VARCHAR, false, false)

        /**
         * The parameter <code>public.addgeometrycolumn.new_dim</code>.
         */
        val NEW_DIM: Parameter<Int?> = Internal.createParameter("new_dim", SQLDataType.INTEGER, false, false)

        /**
         * The parameter <code>public.addgeometrycolumn.use_typmod</code>.
         */
        val USE_TYPMOD: Parameter<Boolean?> =
            Internal.createParameter(
                "use_typmod",
                SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)),
                true,
                false
            )
    }

    init {
        returnParameter = Addgeometrycolumn2.RETURN_VALUE
        addInParameter(Addgeometrycolumn2.SCHEMA_NAME)
        addInParameter(Addgeometrycolumn2.TABLE_NAME)
        addInParameter(Addgeometrycolumn2.COLUMN_NAME)
        addInParameter(Addgeometrycolumn2.NEW_SRID)
        addInParameter(Addgeometrycolumn2.NEW_TYPE)
        addInParameter(Addgeometrycolumn2.NEW_DIM)
        addInParameter(Addgeometrycolumn2.USE_TYPMOD)
        setOverloaded(true)
    }

    /**
     * Set the <code>schema_name</code> parameter IN value to the routine
     */
    fun setSchemaName(value: String?): Unit = setValue(Addgeometrycolumn2.SCHEMA_NAME, value)

    /**
     * Set the <code>schema_name</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setSchemaName(field: Field<String?>) {
        setField(Addgeometrycolumn2.SCHEMA_NAME, field)
    }

    /**
     * Set the <code>table_name</code> parameter IN value to the routine
     */
    fun setTableName(value: String?): Unit = setValue(Addgeometrycolumn2.TABLE_NAME, value)

    /**
     * Set the <code>table_name</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setTableName(field: Field<String?>) {
        setField(Addgeometrycolumn2.TABLE_NAME, field)
    }

    /**
     * Set the <code>column_name</code> parameter IN value to the routine
     */
    fun setColumnName(value: String?): Unit = setValue(Addgeometrycolumn2.COLUMN_NAME, value)

    /**
     * Set the <code>column_name</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setColumnName(field: Field<String?>) {
        setField(Addgeometrycolumn2.COLUMN_NAME, field)
    }

    /**
     * Set the <code>new_srid</code> parameter IN value to the routine
     */
    fun setNewSrid(value: Int?): Unit = setValue(Addgeometrycolumn2.NEW_SRID, value)

    /**
     * Set the <code>new_srid</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setNewSrid(field: Field<Int?>) {
        setField(Addgeometrycolumn2.NEW_SRID, field)
    }

    /**
     * Set the <code>new_type</code> parameter IN value to the routine
     */
    fun setNewType(value: String?): Unit = setValue(Addgeometrycolumn2.NEW_TYPE, value)

    /**
     * Set the <code>new_type</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setNewType(field: Field<String?>) {
        setField(Addgeometrycolumn2.NEW_TYPE, field)
    }

    /**
     * Set the <code>new_dim</code> parameter IN value to the routine
     */
    fun setNewDim(value: Int?): Unit = setValue(Addgeometrycolumn2.NEW_DIM, value)

    /**
     * Set the <code>new_dim</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setNewDim(field: Field<Int?>) {
        setField(Addgeometrycolumn2.NEW_DIM, field)
    }

    /**
     * Set the <code>use_typmod</code> parameter IN value to the routine
     */
    fun setUseTypmod(value: Boolean?): Unit = setValue(Addgeometrycolumn2.USE_TYPMOD, value)

    /**
     * Set the <code>use_typmod</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setUseTypmod(field: Field<Boolean?>) {
        setField(Addgeometrycolumn2.USE_TYPMOD, field)
    }
}
