/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

@Deprecated(
    message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
)
@Suppress("warnings")
open class Box2d1 :
    AbstractRoutine<Any>("box2d", Public.PUBLIC, DSL.comment(""), DefaultDataType.getDefaultDataType("\"public\".\"box2d\"")) {
    companion object {
        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val RETURN_VALUE: Parameter<Any?> =
            Internal.createParameter(
                "RETURN_VALUE",
                DefaultDataType.getDefaultDataType("\"public\".\"box2d\""),
                false,
                false
            )

        /**
         * The parameter <code>public.box2d._1</code>.
         */
        val _1: Parameter<Geometry?> = Internal.createParameter("_1", SQLDataType.GEOMETRY, false, true)
    }

    init {
        returnParameter = Box2d1.RETURN_VALUE
        addInParameter(Box2d1._1)
        setOverloaded(true)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Geometry?): Unit = setValue(Box2d1._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Geometry?>) {
        setField(Box2d1._1, field)
    }
}
