/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Dropgeometrytable2 : AbstractRoutine<String>("dropgeometrytable", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter <code>public.dropgeometrytable.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        /**
         * The parameter <code>public.dropgeometrytable.schema_name</code>.
         */
        val SCHEMA_NAME: Parameter<String?> = Internal.createParameter("schema_name", SQLDataType.VARCHAR, false, false)

        /**
         * The parameter <code>public.dropgeometrytable.table_name</code>.
         */
        val TABLE_NAME: Parameter<String?> = Internal.createParameter("table_name", SQLDataType.VARCHAR, false, false)
    }

    init {
        returnParameter = Dropgeometrytable2.RETURN_VALUE
        addInParameter(Dropgeometrytable2.SCHEMA_NAME)
        addInParameter(Dropgeometrytable2.TABLE_NAME)
        setOverloaded(true)
    }

    /**
     * Set the <code>schema_name</code> parameter IN value to the routine
     */
    fun setSchemaName(value: String?): Unit = setValue(Dropgeometrytable2.SCHEMA_NAME, value)

    /**
     * Set the <code>schema_name</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setSchemaName(field: Field<String?>) {
        setField(Dropgeometrytable2.SCHEMA_NAME, field)
    }

    /**
     * Set the <code>table_name</code> parameter IN value to the routine
     */
    fun setTableName(value: String?): Unit = setValue(Dropgeometrytable2.TABLE_NAME, value)

    /**
     * Set the <code>table_name</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setTableName(field: Field<String?>) {
        setField(Dropgeometrytable2.TABLE_NAME, field)
    }
}
