/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Dropgeometrycolumn3 : AbstractRoutine<String>("dropgeometrycolumn", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter <code>public.dropgeometrycolumn.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        /**
         * The parameter <code>public.dropgeometrycolumn.table_name</code>.
         */
        val TABLE_NAME: Parameter<String?> = Internal.createParameter("table_name", SQLDataType.VARCHAR, false, false)

        /**
         * The parameter <code>public.dropgeometrycolumn.column_name</code>.
         */
        val COLUMN_NAME: Parameter<String?> = Internal.createParameter("column_name", SQLDataType.VARCHAR, false, false)
    }

    init {
        returnParameter = Dropgeometrycolumn3.RETURN_VALUE
        addInParameter(Dropgeometrycolumn3.TABLE_NAME)
        addInParameter(Dropgeometrycolumn3.COLUMN_NAME)
        setOverloaded(true)
    }

    /**
     * Set the <code>table_name</code> parameter IN value to the routine
     */
    fun setTableName(value: String?): Unit = setValue(Dropgeometrycolumn3.TABLE_NAME, value)

    /**
     * Set the <code>table_name</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setTableName(field: Field<String?>) {
        setField(Dropgeometrycolumn3.TABLE_NAME, field)
    }

    /**
     * Set the <code>column_name</code> parameter IN value to the routine
     */
    fun setColumnName(value: String?): Unit = setValue(Dropgeometrycolumn3.COLUMN_NAME, value)

    /**
     * Set the <code>column_name</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setColumnName(field: Field<String?>) {
        setField(Dropgeometrycolumn3.COLUMN_NAME, field)
    }
}
