/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class FindSrid : AbstractRoutine<Int>("find_srid", Public.PUBLIC, DSL.comment(""), SQLDataType.INTEGER) {
    companion object {
        /**
         * The parameter <code>public.find_srid.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Int?> = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false)

        /**
         * The parameter <code>public.find_srid._1</code>.
         */
        val _1: Parameter<String?> = Internal.createParameter("_1", SQLDataType.VARCHAR, false, true)

        /**
         * The parameter <code>public.find_srid._2</code>.
         */
        val _2: Parameter<String?> = Internal.createParameter("_2", SQLDataType.VARCHAR, false, true)

        /**
         * The parameter <code>public.find_srid._3</code>.
         */
        val _3: Parameter<String?> = Internal.createParameter("_3", SQLDataType.VARCHAR, false, true)
    }

    init {
        returnParameter = FindSrid.RETURN_VALUE
        addInParameter(FindSrid._1)
        addInParameter(FindSrid._2)
        addInParameter(FindSrid._3)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: String?): Unit = setValue(FindSrid._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<String?>) {
        setField(FindSrid._1, field)
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    fun set__2(value: String?): Unit = setValue(FindSrid._2, value)

    /**
     * Set the <code>_2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__2(field: Field<String?>) {
        setField(FindSrid._2, field)
    }

    /**
     * Set the <code>_3</code> parameter IN value to the routine
     */
    fun set__3(value: String?): Unit = setValue(FindSrid._3, value)

    /**
     * Set the <code>_3</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__3(field: Field<String?>) {
        setField(FindSrid._3, field)
    }
}
