/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.types.YearToSecond

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GbtIntvDistance : AbstractRoutine<Double>("gbt_intv_distance", Public.PUBLIC, DSL.comment(""), SQLDataType.DOUBLE) {
    companion object {
        /**
         * The parameter <code>public.gbt_intv_distance.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Double?> = Internal.createParameter("RETURN_VALUE", SQLDataType.DOUBLE, false, false)

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val _1: Parameter<Any?> =
            Internal.createParameter(
                "_1",
                DefaultDataType.getDefaultDataType("\"pg_catalog\".\"internal\""),
                false,
                true
            )

        /**
         * The parameter <code>public.gbt_intv_distance._2</code>.
         */
        val _2: Parameter<YearToSecond?> = Internal.createParameter("_2", SQLDataType.INTERVAL, false, true)

        /**
         * The parameter <code>public.gbt_intv_distance._3</code>.
         */
        val _3: Parameter<Short?> = Internal.createParameter("_3", SQLDataType.SMALLINT, false, true)

        /**
         * The parameter <code>public.gbt_intv_distance._4</code>.
         */
        val _4: Parameter<Long?> = Internal.createParameter("_4", SQLDataType.BIGINT, false, true)

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val _5: Parameter<Any?> =
            Internal.createParameter(
                "_5",
                DefaultDataType.getDefaultDataType("\"pg_catalog\".\"internal\""),
                false,
                true
            )
    }

    init {
        returnParameter = GbtIntvDistance.RETURN_VALUE
        addInParameter(GbtIntvDistance._1)
        addInParameter(GbtIntvDistance._2)
        addInParameter(GbtIntvDistance._3)
        addInParameter(GbtIntvDistance._4)
        addInParameter(GbtIntvDistance._5)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Any?): Unit = setValue(GbtIntvDistance._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Any?>) {
        setField(GbtIntvDistance._1, field)
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    fun set__2(value: YearToSecond?): Unit = setValue(GbtIntvDistance._2, value)

    /**
     * Set the <code>_2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__2(field: Field<YearToSecond?>) {
        setField(GbtIntvDistance._2, field)
    }

    /**
     * Set the <code>_3</code> parameter IN value to the routine
     */
    fun set__3(value: Short?): Unit = setValue(GbtIntvDistance._3, value)

    /**
     * Set the <code>_3</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__3(field: Field<Short?>) {
        setField(GbtIntvDistance._3, field)
    }

    /**
     * Set the <code>_4</code> parameter IN value to the routine
     */
    fun set__4(value: Long?): Unit = setValue(GbtIntvDistance._4, value)

    /**
     * Set the <code>_4</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__4(field: Field<Long?>) {
        setField(GbtIntvDistance._4, field)
    }

    /**
     * Set the <code>_5</code> parameter IN value to the routine
     */
    fun set__5(value: Any?): Unit = setValue(GbtIntvDistance._5, value)

    /**
     * Set the <code>_5</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__5(field: Field<Any?>) {
        setField(GbtIntvDistance._5, field)
    }
}
