/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal

import yayauheny.by.Public

@Deprecated(
    message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
)
@Suppress("warnings")
open class GbtNumericSame :
    AbstractRoutine<Any>(
        "gbt_numeric_same",
        Public.PUBLIC,
        DSL.comment(""),
        DefaultDataType.getDefaultDataType("\"pg_catalog\".\"internal\"")
    ) {
    companion object {
        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val RETURN_VALUE: Parameter<Any?> =
            Internal.createParameter(
                "RETURN_VALUE",
                DefaultDataType.getDefaultDataType("\"pg_catalog\".\"internal\""),
                false,
                false
            )

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val _1: Parameter<Any?> =
            Internal.createParameter(
                "_1",
                DefaultDataType.getDefaultDataType("\"public\".\"gbtreekey_var\""),
                false,
                true
            )

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val _2: Parameter<Any?> =
            Internal.createParameter(
                "_2",
                DefaultDataType.getDefaultDataType("\"public\".\"gbtreekey_var\""),
                false,
                true
            )

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val _3: Parameter<Any?> =
            Internal.createParameter(
                "_3",
                DefaultDataType.getDefaultDataType("\"pg_catalog\".\"internal\""),
                false,
                true
            )
    }

    init {
        returnParameter = GbtNumericSame.RETURN_VALUE
        addInParameter(GbtNumericSame._1)
        addInParameter(GbtNumericSame._2)
        addInParameter(GbtNumericSame._3)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Any?): Unit = setValue(GbtNumericSame._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Any?>) {
        setField(GbtNumericSame._1, field)
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    fun set__2(value: Any?): Unit = setValue(GbtNumericSame._2, value)

    /**
     * Set the <code>_2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__2(field: Field<Any?>) {
        setField(GbtNumericSame._2, field)
    }

    /**
     * Set the <code>_3</code> parameter IN value to the routine
     */
    fun set__3(value: Any?): Unit = setValue(GbtNumericSame._3, value)

    /**
     * Set the <code>_3</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__3(field: Field<Any?>) {
        setField(GbtNumericSame._3, field)
    }
}
