/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal

import yayauheny.by.Public

@Deprecated(
    message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
)
@Suppress("warnings")
open class Gbtreekey16Out :
    AbstractRoutine<Any>(
        "gbtreekey16_out",
        Public.PUBLIC,
        DSL.comment(""),
        DefaultDataType.getDefaultDataType("\"pg_catalog\".\"cstring\"")
    ) {
    companion object {
        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val RETURN_VALUE: Parameter<Any?> =
            Internal.createParameter(
                "RETURN_VALUE",
                DefaultDataType.getDefaultDataType("\"pg_catalog\".\"cstring\""),
                false,
                false
            )

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val _1: Parameter<Any?> =
            Internal.createParameter(
                "_1",
                DefaultDataType.getDefaultDataType("\"public\".\"gbtreekey16\""),
                false,
                true
            )
    }

    init {
        returnParameter = Gbtreekey16Out.RETURN_VALUE
        addInParameter(Gbtreekey16Out._1)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Any?): Unit = setValue(Gbtreekey16Out._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Any?>) {
        setField(Gbtreekey16Out._1, field)
    }
}
