/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GeometrySpgistPicksplit_3d : AbstractRoutine<java.lang.Void>("geometry_spgist_picksplit_3d", Public.PUBLIC, DSL.comment("")) {
    companion object {
        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val _1: Parameter<Any?> =
            Internal.createParameter(
                "_1",
                DefaultDataType.getDefaultDataType("\"pg_catalog\".\"internal\""),
                false,
                true
            )

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val _2: Parameter<Any?> =
            Internal.createParameter(
                "_2",
                DefaultDataType.getDefaultDataType("\"pg_catalog\".\"internal\""),
                false,
                true
            )
    }

    init {
        addInParameter(GeometrySpgistPicksplit_3d._1)
        addInParameter(GeometrySpgistPicksplit_3d._2)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Any?): Unit = setValue(GeometrySpgistPicksplit_3d._1, value)

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    fun set__2(value: Any?): Unit = setValue(GeometrySpgistPicksplit_3d._2, value)
}
