/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GeometryContains_3d : AbstractRoutine<Boolean>("geometry_contains_3d", Public.PUBLIC, DSL.comment(""), SQLDataType.BOOLEAN) {
    companion object {
        /**
         * The parameter <code>public.geometry_contains_3d.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Boolean?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BOOLEAN, false, false)

        /**
         * The parameter <code>public.geometry_contains_3d.geom1</code>.
         */
        val GEOM1: Parameter<Geometry?> = Internal.createParameter("geom1", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.geometry_contains_3d.geom2</code>.
         */
        val GEOM2: Parameter<Geometry?> = Internal.createParameter("geom2", SQLDataType.GEOMETRY, false, false)
    }

    init {
        returnParameter = GeometryContains_3d.RETURN_VALUE
        addInParameter(GeometryContains_3d.GEOM1)
        addInParameter(GeometryContains_3d.GEOM2)
    }

    /**
     * Set the <code>geom1</code> parameter IN value to the routine
     */
    fun setGeom1(value: Geometry?): Unit = setValue(GeometryContains_3d.GEOM1, value)

    /**
     * Set the <code>geom1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom1(field: Field<Geometry?>) {
        setField(GeometryContains_3d.GEOM1, field)
    }

    /**
     * Set the <code>geom2</code> parameter IN value to the routine
     */
    fun setGeom2(value: Geometry?): Unit = setValue(GeometryContains_3d.GEOM2, value)

    /**
     * Set the <code>geom2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom2(field: Field<Geometry?>) {
        setField(GeometryContains_3d.GEOM2, field)
    }
}
