/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class PopulateGeometryColumns1 :
    AbstractRoutine<String>("populate_geometry_columns", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter
         * <code>public.populate_geometry_columns.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        /**
         * The parameter
         * <code>public.populate_geometry_columns.use_typmod</code>.
         */
        val USE_TYPMOD: Parameter<Boolean?> =
            Internal.createParameter(
                "use_typmod",
                SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)),
                true,
                false
            )
    }

    init {
        returnParameter = PopulateGeometryColumns1.RETURN_VALUE
        addInParameter(PopulateGeometryColumns1.USE_TYPMOD)
        setOverloaded(true)
    }

    /**
     * Set the <code>use_typmod</code> parameter IN value to the routine
     */
    fun setUseTypmod(value: Boolean?): Unit = setValue(PopulateGeometryColumns1.USE_TYPMOD, value)

    /**
     * Set the <code>use_typmod</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setUseTypmod(field: Field<Boolean?>) {
        setField(PopulateGeometryColumns1.USE_TYPMOD, field)
    }
}
