/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class PostgisDropbbox : AbstractRoutine<Geometry>("postgis_dropbbox", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.postgis_dropbbox.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.postgis_dropbbox._1</code>.
         */
        val _1: Parameter<Geometry?> = Internal.createParameter("_1", SQLDataType.GEOMETRY, false, true)
    }

    init {
        returnParameter = PostgisDropbbox.RETURN_VALUE
        addInParameter(PostgisDropbbox._1)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Geometry?): Unit = setValue(PostgisDropbbox._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Geometry?>) {
        setField(PostgisDropbbox._1, field)
    }
}
