/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class PostgisFullVersion : AbstractRoutine<String>("postgis_full_version", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter <code>public.postgis_full_version.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)
    }

    init {
        returnParameter = PostgisFullVersion.RETURN_VALUE
    }
}
