/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class PostgisExtensionsUpgrade :
    AbstractRoutine<String>("postgis_extensions_upgrade", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter
         * <code>public.postgis_extensions_upgrade.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        /**
         * The parameter
         * <code>public.postgis_extensions_upgrade.target_version</code>.
         */
        val TARGET_VERSION: Parameter<String?> =
            Internal.createParameter(
                "target_version",
                SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL::text"), SQLDataType.CLOB)),
                true,
                false
            )
    }

    init {
        returnParameter = PostgisExtensionsUpgrade.RETURN_VALUE
        addInParameter(PostgisExtensionsUpgrade.TARGET_VERSION)
    }

    /**
     * Set the <code>target_version</code> parameter IN value to the routine
     */
    fun setTargetVersion(value: String?): Unit = setValue(PostgisExtensionsUpgrade.TARGET_VERSION, value)

    /**
     * Set the <code>target_version</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setTargetVersion(field: Field<String?>) {
        setField(PostgisExtensionsUpgrade.TARGET_VERSION, field)
    }
}
