/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

@Deprecated(
    message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
)
@Suppress("warnings")
open class St_3dmakebox :
    AbstractRoutine<Any>("st_3dmakebox", Public.PUBLIC, DSL.comment(""), DefaultDataType.getDefaultDataType("\"public\".\"box3d\"")) {
    companion object {
        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val RETURN_VALUE: Parameter<Any?> =
            Internal.createParameter(
                "RETURN_VALUE",
                DefaultDataType.getDefaultDataType("\"public\".\"box3d\""),
                false,
                false
            )

        /**
         * The parameter <code>public.st_3dmakebox.geom1</code>.
         */
        val GEOM1: Parameter<Geometry?> = Internal.createParameter("geom1", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_3dmakebox.geom2</code>.
         */
        val GEOM2: Parameter<Geometry?> = Internal.createParameter("geom2", SQLDataType.GEOMETRY, false, false)
    }

    init {
        returnParameter = St_3dmakebox.RETURN_VALUE
        addInParameter(St_3dmakebox.GEOM1)
        addInParameter(St_3dmakebox.GEOM2)
    }

    /**
     * Set the <code>geom1</code> parameter IN value to the routine
     */
    fun setGeom1(value: Geometry?): Unit = setValue(St_3dmakebox.GEOM1, value)

    /**
     * Set the <code>geom1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom1(field: Field<Geometry?>) {
        setField(St_3dmakebox.GEOM1, field)
    }

    /**
     * Set the <code>geom2</code> parameter IN value to the routine
     */
    fun setGeom2(value: Geometry?): Unit = setValue(St_3dmakebox.GEOM2, value)

    /**
     * Set the <code>geom2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom2(field: Field<Geometry?>) {
        setField(St_3dmakebox.GEOM2, field)
    }
}
