/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StAsewkt3 : AbstractRoutine<String>("st_asewkt", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter <code>public.st_asewkt.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val _1: Parameter<Any?> =
            Internal.createParameter(
                "_1",
                DefaultDataType.getDefaultDataType("\"public\".\"geography\""),
                false,
                true
            )
    }

    init {
        returnParameter = StAsewkt3.RETURN_VALUE
        addInParameter(StAsewkt3._1)
        setOverloaded(true)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Any?): Unit = setValue(StAsewkt3._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Any?>) {
        setField(StAsewkt3._1, field)
    }
}
