/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StAssvg1 : AbstractRoutine<String>("st_assvg", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter <code>public.st_assvg.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        /**
         * The parameter <code>public.st_assvg.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_assvg.rel</code>.
         */
        val REL: Parameter<Int?> =
            Internal.createParameter(
                "rel",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_assvg.maxdecimaldigits</code>.
         */
        val MAXDECIMALDIGITS: Parameter<Int?> =
            Internal.createParameter(
                "maxdecimaldigits",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("15"), SQLDataType.INTEGER)),
                true,
                false
            )
    }

    init {
        returnParameter = StAssvg1.RETURN_VALUE
        addInParameter(StAssvg1.GEOM)
        addInParameter(StAssvg1.REL)
        addInParameter(StAssvg1.MAXDECIMALDIGITS)
        setOverloaded(true)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StAssvg1.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StAssvg1.GEOM, field)
    }

    /**
     * Set the <code>rel</code> parameter IN value to the routine
     */
    fun setRel(value: Int?): Unit = setValue(StAssvg1.REL, value)

    /**
     * Set the <code>rel</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setRel(field: Field<Int?>) {
        setField(StAssvg1.REL, field)
    }

    /**
     * Set the <code>maxdecimaldigits</code> parameter IN value to the routine
     */
    fun setMaxdecimaldigits(value: Int?): Unit = setValue(StAssvg1.MAXDECIMALDIGITS, value)

    /**
     * Set the <code>maxdecimaldigits</code> parameter to the function to be
     * used with a {@link org.jooq.Select} statement
     */
    fun setMaxdecimaldigits(field: Field<Int?>) {
        setField(StAssvg1.MAXDECIMALDIGITS, field)
    }
}
