/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StAsgml2 : AbstractRoutine<String>("st_asgml", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter <code>public.st_asgml.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        /**
         * The parameter <code>public.st_asgml.version</code>.
         */
        val VERSION: Parameter<Int?> = Internal.createParameter("version", SQLDataType.INTEGER, false, false)

        /**
         * The parameter <code>public.st_asgml.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_asgml.maxdecimaldigits</code>.
         */
        val MAXDECIMALDIGITS: Parameter<Int?> =
            Internal.createParameter(
                "maxdecimaldigits",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("15"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_asgml.options</code>.
         */
        val OPTIONS: Parameter<Int?> =
            Internal.createParameter(
                "options",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_asgml.nprefix</code>.
         */
        val NPREFIX: Parameter<String?> =
            Internal.createParameter(
                "nprefix",
                SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL::text"), SQLDataType.CLOB)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_asgml.id</code>.
         */
        val ID: Parameter<String?> =
            Internal.createParameter(
                "id",
                SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL::text"), SQLDataType.CLOB)),
                true,
                false
            )
    }

    init {
        returnParameter = StAsgml2.RETURN_VALUE
        addInParameter(StAsgml2.VERSION)
        addInParameter(StAsgml2.GEOM)
        addInParameter(StAsgml2.MAXDECIMALDIGITS)
        addInParameter(StAsgml2.OPTIONS)
        addInParameter(StAsgml2.NPREFIX)
        addInParameter(StAsgml2.ID)
        setOverloaded(true)
    }

    /**
     * Set the <code>version</code> parameter IN value to the routine
     */
    fun setVersion(value: Int?): Unit = setValue(StAsgml2.VERSION, value)

    /**
     * Set the <code>version</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setVersion(field: Field<Int?>) {
        setField(StAsgml2.VERSION, field)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StAsgml2.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StAsgml2.GEOM, field)
    }

    /**
     * Set the <code>maxdecimaldigits</code> parameter IN value to the routine
     */
    fun setMaxdecimaldigits(value: Int?): Unit = setValue(StAsgml2.MAXDECIMALDIGITS, value)

    /**
     * Set the <code>maxdecimaldigits</code> parameter to the function to be
     * used with a {@link org.jooq.Select} statement
     */
    fun setMaxdecimaldigits(field: Field<Int?>) {
        setField(StAsgml2.MAXDECIMALDIGITS, field)
    }

    /**
     * Set the <code>options</code> parameter IN value to the routine
     */
    fun setOptions(value: Int?): Unit = setValue(StAsgml2.OPTIONS, value)

    /**
     * Set the <code>options</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setOptions(field: Field<Int?>) {
        setField(StAsgml2.OPTIONS, field)
    }

    /**
     * Set the <code>nprefix</code> parameter IN value to the routine
     */
    fun setNprefix(value: String?): Unit = setValue(StAsgml2.NPREFIX, value)

    /**
     * Set the <code>nprefix</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setNprefix(field: Field<String?>) {
        setField(StAsgml2.NPREFIX, field)
    }

    /**
     * Set the <code>id</code> parameter IN value to the routine
     */
    fun setId(value: String?): Unit = setValue(StAsgml2.ID, value)

    /**
     * Set the <code>id</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setId(field: Field<String?>) {
        setField(StAsgml2.ID, field)
    }
}
