/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StAstwkb2 : AbstractRoutine<ByteArray>("st_astwkb", Public.PUBLIC, DSL.comment(""), SQLDataType.BLOB) {
    companion object {
        /**
         * The parameter <code>public.st_astwkb.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<ByteArray?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BLOB, false, false)

        /**
         * The parameter <code>public.st_astwkb.geom</code>.
         */
        val GEOM: Parameter<Array<Geometry?>?> = Internal.createParameter("geom", SQLDataType.GEOMETRY.array(), false, false)

        /**
         * The parameter <code>public.st_astwkb.ids</code>.
         */
        val IDS: Parameter<Array<Long?>?> = Internal.createParameter("ids", SQLDataType.BIGINT.array(), false, false)

        /**
         * The parameter <code>public.st_astwkb.prec</code>.
         */
        val PREC: Parameter<Int?> =
            Internal.createParameter(
                "prec",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL::integer"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_astwkb.prec_z</code>.
         */
        val PREC_Z: Parameter<Int?> =
            Internal.createParameter(
                "prec_z",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL::integer"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_astwkb.prec_m</code>.
         */
        val PREC_M: Parameter<Int?> =
            Internal.createParameter(
                "prec_m",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL::integer"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_astwkb.with_sizes</code>.
         */
        val WITH_SIZES: Parameter<Boolean?> =
            Internal.createParameter(
                "with_sizes",
                SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("NULL::boolean"), SQLDataType.BOOLEAN)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_astwkb.with_boxes</code>.
         */
        val WITH_BOXES: Parameter<Boolean?> =
            Internal.createParameter(
                "with_boxes",
                SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("NULL::boolean"), SQLDataType.BOOLEAN)),
                true,
                false
            )
    }

    init {
        returnParameter = StAstwkb2.RETURN_VALUE
        addInParameter(StAstwkb2.GEOM)
        addInParameter(StAstwkb2.IDS)
        addInParameter(StAstwkb2.PREC)
        addInParameter(StAstwkb2.PREC_Z)
        addInParameter(StAstwkb2.PREC_M)
        addInParameter(StAstwkb2.WITH_SIZES)
        addInParameter(StAstwkb2.WITH_BOXES)
        setOverloaded(true)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Array<Geometry?>?): Unit = setValue(StAstwkb2.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Array<Geometry?>?>) {
        setField(StAstwkb2.GEOM, field)
    }

    /**
     * Set the <code>ids</code> parameter IN value to the routine
     */
    fun setIds(value: Array<Long?>?): Unit = setValue(StAstwkb2.IDS, value)

    /**
     * Set the <code>ids</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setIds(field: Field<Array<Long?>?>) {
        setField(StAstwkb2.IDS, field)
    }

    /**
     * Set the <code>prec</code> parameter IN value to the routine
     */
    fun setPrec(value: Int?): Unit = setValue(StAstwkb2.PREC, value)

    /**
     * Set the <code>prec</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setPrec(field: Field<Int?>) {
        setField(StAstwkb2.PREC, field)
    }

    /**
     * Set the <code>prec_z</code> parameter IN value to the routine
     */
    fun setPrecZ(value: Int?): Unit = setValue(StAstwkb2.PREC_Z, value)

    /**
     * Set the <code>prec_z</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setPrecZ(field: Field<Int?>) {
        setField(StAstwkb2.PREC_Z, field)
    }

    /**
     * Set the <code>prec_m</code> parameter IN value to the routine
     */
    fun setPrecM(value: Int?): Unit = setValue(StAstwkb2.PREC_M, value)

    /**
     * Set the <code>prec_m</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setPrecM(field: Field<Int?>) {
        setField(StAstwkb2.PREC_M, field)
    }

    /**
     * Set the <code>with_sizes</code> parameter IN value to the routine
     */
    fun setWithSizes(value: Boolean?): Unit = setValue(StAstwkb2.WITH_SIZES, value)

    /**
     * Set the <code>with_sizes</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setWithSizes(field: Field<Boolean?>) {
        setField(StAstwkb2.WITH_SIZES, field)
    }

    /**
     * Set the <code>with_boxes</code> parameter IN value to the routine
     */
    fun setWithBoxes(value: Boolean?): Unit = setValue(StAstwkb2.WITH_BOXES, value)

    /**
     * Set the <code>with_boxes</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setWithBoxes(field: Field<Boolean?>) {
        setField(StAstwkb2.WITH_BOXES, field)
    }
}
