/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StAsgml4 : AbstractRoutine<String>("st_asgml", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter <code>public.st_asgml.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val GEOG: Parameter<Any?> =
            Internal.createParameter(
                "geog",
                DefaultDataType.getDefaultDataType("\"public\".\"geography\""),
                false,
                false
            )

        /**
         * The parameter <code>public.st_asgml.maxdecimaldigits</code>.
         */
        val MAXDECIMALDIGITS: Parameter<Int?> =
            Internal.createParameter(
                "maxdecimaldigits",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("15"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_asgml.options</code>.
         */
        val OPTIONS: Parameter<Int?> =
            Internal.createParameter(
                "options",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_asgml.nprefix</code>.
         */
        val NPREFIX: Parameter<String?> =
            Internal.createParameter(
                "nprefix",
                SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("'gml'::text"), SQLDataType.CLOB)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_asgml.id</code>.
         */
        val ID: Parameter<String?> =
            Internal.createParameter(
                "id",
                SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)),
                true,
                false
            )
    }

    init {
        returnParameter = StAsgml4.RETURN_VALUE
        addInParameter(StAsgml4.GEOG)
        addInParameter(StAsgml4.MAXDECIMALDIGITS)
        addInParameter(StAsgml4.OPTIONS)
        addInParameter(StAsgml4.NPREFIX)
        addInParameter(StAsgml4.ID)
        setOverloaded(true)
    }

    /**
     * Set the <code>geog</code> parameter IN value to the routine
     */
    fun setGeog(value: Any?): Unit = setValue(StAsgml4.GEOG, value)

    /**
     * Set the <code>geog</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeog(field: Field<Any?>) {
        setField(StAsgml4.GEOG, field)
    }

    /**
     * Set the <code>maxdecimaldigits</code> parameter IN value to the routine
     */
    fun setMaxdecimaldigits(value: Int?): Unit = setValue(StAsgml4.MAXDECIMALDIGITS, value)

    /**
     * Set the <code>maxdecimaldigits</code> parameter to the function to be
     * used with a {@link org.jooq.Select} statement
     */
    fun setMaxdecimaldigits(field: Field<Int?>) {
        setField(StAsgml4.MAXDECIMALDIGITS, field)
    }

    /**
     * Set the <code>options</code> parameter IN value to the routine
     */
    fun setOptions(value: Int?): Unit = setValue(StAsgml4.OPTIONS, value)

    /**
     * Set the <code>options</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setOptions(field: Field<Int?>) {
        setField(StAsgml4.OPTIONS, field)
    }

    /**
     * Set the <code>nprefix</code> parameter IN value to the routine
     */
    fun setNprefix(value: String?): Unit = setValue(StAsgml4.NPREFIX, value)

    /**
     * Set the <code>nprefix</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setNprefix(field: Field<String?>) {
        setField(StAsgml4.NPREFIX, field)
    }

    /**
     * Set the <code>id</code> parameter IN value to the routine
     */
    fun setId(value: String?): Unit = setValue(StAsgml4.ID, value)

    /**
     * Set the <code>id</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setId(field: Field<String?>) {
        setField(StAsgml4.ID, field)
    }
}
