/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StAsgeojson1 : AbstractRoutine<String>("st_asgeojson", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter <code>public.st_asgeojson.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        /**
         * The parameter <code>public.st_asgeojson.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_asgeojson.maxdecimaldigits</code>.
         */
        val MAXDECIMALDIGITS: Parameter<Int?> =
            Internal.createParameter(
                "maxdecimaldigits",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("9"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_asgeojson.options</code>.
         */
        val OPTIONS: Parameter<Int?> =
            Internal.createParameter(
                "options",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("8"), SQLDataType.INTEGER)),
                true,
                false
            )
    }

    init {
        returnParameter = StAsgeojson1.RETURN_VALUE
        addInParameter(StAsgeojson1.GEOM)
        addInParameter(StAsgeojson1.MAXDECIMALDIGITS)
        addInParameter(StAsgeojson1.OPTIONS)
        setOverloaded(true)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StAsgeojson1.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StAsgeojson1.GEOM, field)
    }

    /**
     * Set the <code>maxdecimaldigits</code> parameter IN value to the routine
     */
    fun setMaxdecimaldigits(value: Int?): Unit = setValue(StAsgeojson1.MAXDECIMALDIGITS, value)

    /**
     * Set the <code>maxdecimaldigits</code> parameter to the function to be
     * used with a {@link org.jooq.Select} statement
     */
    fun setMaxdecimaldigits(field: Field<Int?>) {
        setField(StAsgeojson1.MAXDECIMALDIGITS, field)
    }

    /**
     * Set the <code>options</code> parameter IN value to the routine
     */
    fun setOptions(value: Int?): Unit = setValue(StAsgeojson1.OPTIONS, value)

    /**
     * Set the <code>options</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setOptions(field: Field<Int?>) {
        setField(StAsgeojson1.OPTIONS, field)
    }
}
