/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StAsmvtgeom : AbstractRoutine<Geometry>("st_asmvtgeom", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_asmvtgeom.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_asmvtgeom.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val BOUNDS: Parameter<Any?> =
            Internal.createParameter(
                "bounds",
                DefaultDataType.getDefaultDataType("\"public\".\"box2d\""),
                false,
                false
            )

        /**
         * The parameter <code>public.st_asmvtgeom.extent</code>.
         */
        val EXTENT: Parameter<Int?> =
            Internal.createParameter(
                "extent",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("4096"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_asmvtgeom.buffer</code>.
         */
        val BUFFER: Parameter<Int?> =
            Internal.createParameter(
                "buffer",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("256"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_asmvtgeom.clip_geom</code>.
         */
        val CLIP_GEOM: Parameter<Boolean?> =
            Internal.createParameter(
                "clip_geom",
                SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)),
                true,
                false
            )
    }

    init {
        returnParameter = StAsmvtgeom.RETURN_VALUE
        addInParameter(StAsmvtgeom.GEOM)
        addInParameter(StAsmvtgeom.BOUNDS)
        addInParameter(StAsmvtgeom.EXTENT)
        addInParameter(StAsmvtgeom.BUFFER)
        addInParameter(StAsmvtgeom.CLIP_GEOM)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StAsmvtgeom.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StAsmvtgeom.GEOM, field)
    }

    /**
     * Set the <code>bounds</code> parameter IN value to the routine
     */
    fun setBounds(value: Any?): Unit = setValue(StAsmvtgeom.BOUNDS, value)

    /**
     * Set the <code>bounds</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setBounds(field: Field<Any?>) {
        setField(StAsmvtgeom.BOUNDS, field)
    }

    /**
     * Set the <code>extent</code> parameter IN value to the routine
     */
    fun setExtent(value: Int?): Unit = setValue(StAsmvtgeom.EXTENT, value)

    /**
     * Set the <code>extent</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setExtent(field: Field<Int?>) {
        setField(StAsmvtgeom.EXTENT, field)
    }

    /**
     * Set the <code>buffer</code> parameter IN value to the routine
     */
    fun setBuffer(value: Int?): Unit = setValue(StAsmvtgeom.BUFFER, value)

    /**
     * Set the <code>buffer</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setBuffer(field: Field<Int?>) {
        setField(StAsmvtgeom.BUFFER, field)
    }

    /**
     * Set the <code>clip_geom</code> parameter IN value to the routine
     */
    fun setClipGeom(value: Boolean?): Unit = setValue(StAsmvtgeom.CLIP_GEOM, value)

    /**
     * Set the <code>clip_geom</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setClipGeom(field: Field<Boolean?>) {
        setField(StAsmvtgeom.CLIP_GEOM, field)
    }
}
