/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StAsencodedpolyline : AbstractRoutine<String>("st_asencodedpolyline", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter <code>public.st_asencodedpolyline.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        /**
         * The parameter <code>public.st_asencodedpolyline.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_asencodedpolyline.nprecision</code>.
         */
        val NPRECISION: Parameter<Int?> =
            Internal.createParameter(
                "nprecision",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("5"), SQLDataType.INTEGER)),
                true,
                false
            )
    }

    init {
        returnParameter = StAsencodedpolyline.RETURN_VALUE
        addInParameter(StAsencodedpolyline.GEOM)
        addInParameter(StAsencodedpolyline.NPRECISION)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StAsencodedpolyline.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StAsencodedpolyline.GEOM, field)
    }

    /**
     * Set the <code>nprecision</code> parameter IN value to the routine
     */
    fun setNprecision(value: Int?): Unit = setValue(StAsencodedpolyline.NPRECISION, value)

    /**
     * Set the <code>nprecision</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setNprecision(field: Field<Int?>) {
        setField(StAsencodedpolyline.NPRECISION, field)
    }
}
