/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StAssvg2 : AbstractRoutine<String>("st_assvg", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter <code>public.st_assvg.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val GEOG: Parameter<Any?> =
            Internal.createParameter(
                "geog",
                DefaultDataType.getDefaultDataType("\"public\".\"geography\""),
                false,
                false
            )

        /**
         * The parameter <code>public.st_assvg.rel</code>.
         */
        val REL: Parameter<Int?> =
            Internal.createParameter(
                "rel",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_assvg.maxdecimaldigits</code>.
         */
        val MAXDECIMALDIGITS: Parameter<Int?> =
            Internal.createParameter(
                "maxdecimaldigits",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("15"), SQLDataType.INTEGER)),
                true,
                false
            )
    }

    init {
        returnParameter = StAssvg2.RETURN_VALUE
        addInParameter(StAssvg2.GEOG)
        addInParameter(StAssvg2.REL)
        addInParameter(StAssvg2.MAXDECIMALDIGITS)
        setOverloaded(true)
    }

    /**
     * Set the <code>geog</code> parameter IN value to the routine
     */
    fun setGeog(value: Any?): Unit = setValue(StAssvg2.GEOG, value)

    /**
     * Set the <code>geog</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeog(field: Field<Any?>) {
        setField(StAssvg2.GEOG, field)
    }

    /**
     * Set the <code>rel</code> parameter IN value to the routine
     */
    fun setRel(value: Int?): Unit = setValue(StAssvg2.REL, value)

    /**
     * Set the <code>rel</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setRel(field: Field<Int?>) {
        setField(StAssvg2.REL, field)
    }

    /**
     * Set the <code>maxdecimaldigits</code> parameter IN value to the routine
     */
    fun setMaxdecimaldigits(value: Int?): Unit = setValue(StAssvg2.MAXDECIMALDIGITS, value)

    /**
     * Set the <code>maxdecimaldigits</code> parameter to the function to be
     * used with a {@link org.jooq.Select} statement
     */
    fun setMaxdecimaldigits(field: Field<Int?>) {
        setField(StAssvg2.MAXDECIMALDIGITS, field)
    }
}
