/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StBoundingdiagonal : AbstractRoutine<Geometry>("st_boundingdiagonal", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_boundingdiagonal.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_boundingdiagonal.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_boundingdiagonal.fits</code>.
         */
        val FITS: Parameter<Boolean?> =
            Internal.createParameter(
                "fits",
                SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)),
                true,
                false
            )
    }

    init {
        returnParameter = StBoundingdiagonal.RETURN_VALUE
        addInParameter(StBoundingdiagonal.GEOM)
        addInParameter(StBoundingdiagonal.FITS)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StBoundingdiagonal.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StBoundingdiagonal.GEOM, field)
    }

    /**
     * Set the <code>fits</code> parameter IN value to the routine
     */
    fun setFits(value: Boolean?): Unit = setValue(StBoundingdiagonal.FITS, value)

    /**
     * Set the <code>fits</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setFits(field: Field<Boolean?>) {
        setField(StBoundingdiagonal.FITS, field)
    }
}
