/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StBuffer1 : AbstractRoutine<Geometry>("st_buffer", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_buffer.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_buffer.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_buffer.radius</code>.
         */
        val RADIUS: Parameter<Double?> = Internal.createParameter("radius", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_buffer.options</code>.
         */
        val OPTIONS: Parameter<String?> =
            Internal.createParameter(
                "options",
                SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)),
                true,
                false
            )
    }

    init {
        returnParameter = StBuffer1.RETURN_VALUE
        addInParameter(StBuffer1.GEOM)
        addInParameter(StBuffer1.RADIUS)
        addInParameter(StBuffer1.OPTIONS)
        setOverloaded(true)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StBuffer1.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StBuffer1.GEOM, field)
    }

    /**
     * Set the <code>radius</code> parameter IN value to the routine
     */
    fun setRadius(value: Double?): Unit = setValue(StBuffer1.RADIUS, value)

    /**
     * Set the <code>radius</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setRadius(field: Field<Double?>) {
        setField(StBuffer1.RADIUS, field)
    }

    /**
     * Set the <code>options</code> parameter IN value to the routine
     */
    fun setOptions(value: String?): Unit = setValue(StBuffer1.OPTIONS, value)

    /**
     * Set the <code>options</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setOptions(field: Field<String?>) {
        setField(StBuffer1.OPTIONS, field)
    }
}
