/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

@Deprecated(
    message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
)
@Suppress("warnings")
open class StBuffer4 :
    AbstractRoutine<Any>("st_buffer", Public.PUBLIC, DSL.comment(""), DefaultDataType.getDefaultDataType("\"public\".\"geography\"")) {
    companion object {
        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val RETURN_VALUE: Parameter<Any?> =
            Internal.createParameter(
                "RETURN_VALUE",
                DefaultDataType.getDefaultDataType("\"public\".\"geography\""),
                false,
                false
            )

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val _1: Parameter<Any?> =
            Internal.createParameter(
                "_1",
                DefaultDataType.getDefaultDataType("\"public\".\"geography\""),
                false,
                true
            )

        /**
         * The parameter <code>public.st_buffer._2</code>.
         */
        val _2: Parameter<Double?> = Internal.createParameter("_2", SQLDataType.DOUBLE, false, true)

        /**
         * The parameter <code>public.st_buffer._3</code>.
         */
        val _3: Parameter<Int?> = Internal.createParameter("_3", SQLDataType.INTEGER, false, true)
    }

    init {
        returnParameter = StBuffer4.RETURN_VALUE
        addInParameter(StBuffer4._1)
        addInParameter(StBuffer4._2)
        addInParameter(StBuffer4._3)
        setOverloaded(true)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Any?): Unit = setValue(StBuffer4._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Any?>) {
        setField(StBuffer4._1, field)
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    fun set__2(value: Double?): Unit = setValue(StBuffer4._2, value)

    /**
     * Set the <code>_2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__2(field: Field<Double?>) {
        setField(StBuffer4._2, field)
    }

    /**
     * Set the <code>_3</code> parameter IN value to the routine
     */
    fun set__3(value: Int?): Unit = setValue(StBuffer4._3, value)

    /**
     * Set the <code>_3</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__3(field: Field<Int?>) {
        setField(StBuffer4._3, field)
    }
}
