/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StClipbybox2d : AbstractRoutine<Geometry>("st_clipbybox2d", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_clipbybox2d.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_clipbybox2d.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val BOX: Parameter<Any?> = Internal.createParameter("box", DefaultDataType.getDefaultDataType("\"public\".\"box2d\""), false, false)
    }

    init {
        returnParameter = StClipbybox2d.RETURN_VALUE
        addInParameter(StClipbybox2d.GEOM)
        addInParameter(StClipbybox2d.BOX)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StClipbybox2d.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StClipbybox2d.GEOM, field)
    }

    /**
     * Set the <code>box</code> parameter IN value to the routine
     */
    fun setBox(value: Any?): Unit = setValue(StClipbybox2d.BOX, value)

    /**
     * Set the <code>box</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setBox(field: Field<Any?>) {
        setField(StClipbybox2d.BOX, field)
    }
}
