/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StClusterwithinwin : AbstractRoutine<Int>("st_clusterwithinwin", Public.PUBLIC, DSL.comment(""), SQLDataType.INTEGER) {
    companion object {
        /**
         * The parameter <code>public.st_clusterwithinwin.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Int?> = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false)

        /**
         * The parameter <code>public.st_clusterwithinwin._1</code>.
         */
        val _1: Parameter<Geometry?> = Internal.createParameter("_1", SQLDataType.GEOMETRY, false, true)

        /**
         * The parameter <code>public.st_clusterwithinwin.distance</code>.
         */
        val DISTANCE: Parameter<Double?> = Internal.createParameter("distance", SQLDataType.DOUBLE, false, false)
    }

    init {
        returnParameter = StClusterwithinwin.RETURN_VALUE
        addInParameter(StClusterwithinwin._1)
        addInParameter(StClusterwithinwin.DISTANCE)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Geometry?): Unit = setValue(StClusterwithinwin._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Geometry?>) {
        setField(StClusterwithinwin._1, field)
    }

    /**
     * Set the <code>distance</code> parameter IN value to the routine
     */
    fun setDistance(value: Double?): Unit = setValue(StClusterwithinwin.DISTANCE, value)

    /**
     * Set the <code>distance</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setDistance(field: Field<Double?>) {
        setField(StClusterwithinwin.DISTANCE, field)
    }
}
