/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StConcavehull : AbstractRoutine<Geometry>("st_concavehull", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_concavehull.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_concavehull.param_geom</code>.
         */
        val PARAM_GEOM: Parameter<Geometry?> = Internal.createParameter("param_geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_concavehull.param_pctconvex</code>.
         */
        val PARAM_PCTCONVEX: Parameter<Double?> = Internal.createParameter("param_pctconvex", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_concavehull.param_allow_holes</code>.
         */
        val PARAM_ALLOW_HOLES: Parameter<Boolean?> =
            Internal.createParameter(
                "param_allow_holes",
                SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)),
                true,
                false
            )
    }

    init {
        returnParameter = StConcavehull.RETURN_VALUE
        addInParameter(StConcavehull.PARAM_GEOM)
        addInParameter(StConcavehull.PARAM_PCTCONVEX)
        addInParameter(StConcavehull.PARAM_ALLOW_HOLES)
    }

    /**
     * Set the <code>param_geom</code> parameter IN value to the routine
     */
    fun setParamGeom(value: Geometry?): Unit = setValue(StConcavehull.PARAM_GEOM, value)

    /**
     * Set the <code>param_geom</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setParamGeom(field: Field<Geometry?>) {
        setField(StConcavehull.PARAM_GEOM, field)
    }

    /**
     * Set the <code>param_pctconvex</code> parameter IN value to the routine
     */
    fun setParamPctconvex(value: Double?): Unit = setValue(StConcavehull.PARAM_PCTCONVEX, value)

    /**
     * Set the <code>param_pctconvex</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setParamPctconvex(field: Field<Double?>) {
        setField(StConcavehull.PARAM_PCTCONVEX, field)
    }

    /**
     * Set the <code>param_allow_holes</code> parameter IN value to the routine
     */
    fun setParamAllowHoles(value: Boolean?): Unit = setValue(StConcavehull.PARAM_ALLOW_HOLES, value)

    /**
     * Set the <code>param_allow_holes</code> parameter to the function to be
     * used with a {@link org.jooq.Select} statement
     */
    fun setParamAllowHoles(field: Field<Boolean?>) {
        setField(StConcavehull.PARAM_ALLOW_HOLES, field)
    }
}
