/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StCurven : AbstractRoutine<Geometry>("st_curven", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_curven.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_curven.geometry</code>.
         */
        val GEOMETRY: Parameter<Geometry?> = Internal.createParameter("geometry", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_curven.i</code>.
         */
        val I: Parameter<Int?> = Internal.createParameter("i", SQLDataType.INTEGER, false, false)
    }

    init {
        returnParameter = StCurven.RETURN_VALUE
        addInParameter(StCurven.GEOMETRY)
        addInParameter(StCurven.I)
    }

    /**
     * Set the <code>geometry</code> parameter IN value to the routine
     */
    fun setGeometry(value: Geometry?): Unit = setValue(StCurven.GEOMETRY, value)

    /**
     * Set the <code>geometry</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeometry(field: Field<Geometry?>) {
        setField(StCurven.GEOMETRY, field)
    }

    /**
     * Set the <code>i</code> parameter IN value to the routine
     */
    fun setI(value: Int?): Unit = setValue(StCurven.I, value)

    /**
     * Set the <code>i</code> parameter to the function to be used with a {@link
     * org.jooq.Select} statement
     */
    fun setI(field: Field<Int?>) {
        setField(StCurven.I, field)
    }
}
