/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StCurvetoline : AbstractRoutine<Geometry>("st_curvetoline", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_curvetoline.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_curvetoline.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_curvetoline.tol</code>.
         */
        val TOL: Parameter<Double?> =
            Internal.createParameter(
                "tol",
                SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("32"), SQLDataType.DOUBLE)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_curvetoline.toltype</code>.
         */
        val TOLTYPE: Parameter<Int?> =
            Internal.createParameter(
                "toltype",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_curvetoline.flags</code>.
         */
        val FLAGS: Parameter<Int?> =
            Internal.createParameter(
                "flags",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)),
                true,
                false
            )
    }

    init {
        returnParameter = StCurvetoline.RETURN_VALUE
        addInParameter(StCurvetoline.GEOM)
        addInParameter(StCurvetoline.TOL)
        addInParameter(StCurvetoline.TOLTYPE)
        addInParameter(StCurvetoline.FLAGS)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StCurvetoline.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StCurvetoline.GEOM, field)
    }

    /**
     * Set the <code>tol</code> parameter IN value to the routine
     */
    fun setTol(value: Double?): Unit = setValue(StCurvetoline.TOL, value)

    /**
     * Set the <code>tol</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setTol(field: Field<Double?>) {
        setField(StCurvetoline.TOL, field)
    }

    /**
     * Set the <code>toltype</code> parameter IN value to the routine
     */
    fun setToltype(value: Int?): Unit = setValue(StCurvetoline.TOLTYPE, value)

    /**
     * Set the <code>toltype</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setToltype(field: Field<Int?>) {
        setField(StCurvetoline.TOLTYPE, field)
    }

    /**
     * Set the <code>flags</code> parameter IN value to the routine
     */
    fun setFlags(value: Int?): Unit = setValue(StCurvetoline.FLAGS, value)

    /**
     * Set the <code>flags</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setFlags(field: Field<Int?>) {
        setField(StCurvetoline.FLAGS, field)
    }
}
