/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StDifference : AbstractRoutine<Geometry>("st_difference", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_difference.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_difference.geom1</code>.
         */
        val GEOM1: Parameter<Geometry?> = Internal.createParameter("geom1", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_difference.geom2</code>.
         */
        val GEOM2: Parameter<Geometry?> = Internal.createParameter("geom2", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_difference.gridsize</code>.
         */
        val GRIDSIZE: Parameter<Double?> =
            Internal.createParameter(
                "gridsize",
                SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("'-1.0'::numeric"), SQLDataType.DOUBLE)),
                true,
                false
            )
    }

    init {
        returnParameter = StDifference.RETURN_VALUE
        addInParameter(StDifference.GEOM1)
        addInParameter(StDifference.GEOM2)
        addInParameter(StDifference.GRIDSIZE)
    }

    /**
     * Set the <code>geom1</code> parameter IN value to the routine
     */
    fun setGeom1(value: Geometry?): Unit = setValue(StDifference.GEOM1, value)

    /**
     * Set the <code>geom1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom1(field: Field<Geometry?>) {
        setField(StDifference.GEOM1, field)
    }

    /**
     * Set the <code>geom2</code> parameter IN value to the routine
     */
    fun setGeom2(value: Geometry?): Unit = setValue(StDifference.GEOM2, value)

    /**
     * Set the <code>geom2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom2(field: Field<Geometry?>) {
        setField(StDifference.GEOM2, field)
    }

    /**
     * Set the <code>gridsize</code> parameter IN value to the routine
     */
    fun setGridsize(value: Double?): Unit = setValue(StDifference.GRIDSIZE, value)

    /**
     * Set the <code>gridsize</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGridsize(field: Field<Double?>) {
        setField(StDifference.GRIDSIZE, field)
    }
}
