/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

@Deprecated(
    message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
)
@Suppress("warnings")
open class StExpand4 :
    AbstractRoutine<Any>("st_expand", Public.PUBLIC, DSL.comment(""), DefaultDataType.getDefaultDataType("\"public\".\"box3d\"")) {
    companion object {
        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val RETURN_VALUE: Parameter<Any?> =
            Internal.createParameter(
                "RETURN_VALUE",
                DefaultDataType.getDefaultDataType("\"public\".\"box3d\""),
                false,
                false
            )

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val BOX: Parameter<Any?> = Internal.createParameter("box", DefaultDataType.getDefaultDataType("\"public\".\"box3d\""), false, false)

        /**
         * The parameter <code>public.st_expand.dx</code>.
         */
        val DX: Parameter<Double?> = Internal.createParameter("dx", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_expand.dy</code>.
         */
        val DY: Parameter<Double?> = Internal.createParameter("dy", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_expand.dz</code>.
         */
        val DZ: Parameter<Double?> =
            Internal.createParameter(
                "dz",
                SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DOUBLE)),
                true,
                false
            )
    }

    init {
        returnParameter = StExpand4.RETURN_VALUE
        addInParameter(StExpand4.BOX)
        addInParameter(StExpand4.DX)
        addInParameter(StExpand4.DY)
        addInParameter(StExpand4.DZ)
        setOverloaded(true)
    }

    /**
     * Set the <code>box</code> parameter IN value to the routine
     */
    fun setBox(value: Any?): Unit = setValue(StExpand4.BOX, value)

    /**
     * Set the <code>box</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setBox(field: Field<Any?>) {
        setField(StExpand4.BOX, field)
    }

    /**
     * Set the <code>dx</code> parameter IN value to the routine
     */
    fun setDx(value: Double?): Unit = setValue(StExpand4.DX, value)

    /**
     * Set the <code>dx</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setDx(field: Field<Double?>) {
        setField(StExpand4.DX, field)
    }

    /**
     * Set the <code>dy</code> parameter IN value to the routine
     */
    fun setDy(value: Double?): Unit = setValue(StExpand4.DY, value)

    /**
     * Set the <code>dy</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setDy(field: Field<Double?>) {
        setField(StExpand4.DY, field)
    }

    /**
     * Set the <code>dz</code> parameter IN value to the routine
     */
    fun setDz(value: Double?): Unit = setValue(StExpand4.DZ, value)

    /**
     * Set the <code>dz</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setDz(field: Field<Double?>) {
        setField(StExpand4.DZ, field)
    }
}
