/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StForce3dm : AbstractRoutine<Geometry>("st_force3dm", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_force3dm.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_force3dm.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_force3dm.mvalue</code>.
         */
        val MVALUE: Parameter<Double?> =
            Internal.createParameter(
                "mvalue",
                SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.DOUBLE)),
                true,
                false
            )
    }

    init {
        returnParameter = StForce3dm.RETURN_VALUE
        addInParameter(StForce3dm.GEOM)
        addInParameter(StForce3dm.MVALUE)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StForce3dm.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StForce3dm.GEOM, field)
    }

    /**
     * Set the <code>mvalue</code> parameter IN value to the routine
     */
    fun setMvalue(value: Double?): Unit = setValue(StForce3dm.MVALUE, value)

    /**
     * Set the <code>mvalue</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setMvalue(field: Field<Double?>) {
        setField(StForce3dm.MVALUE, field)
    }
}
