/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StGeometricmedian : AbstractRoutine<Geometry>("st_geometricmedian", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_geometricmedian.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_geometricmedian.g</code>.
         */
        val G: Parameter<Geometry?> = Internal.createParameter("g", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_geometricmedian.tolerance</code>.
         */
        val TOLERANCE: Parameter<Double?> =
            Internal.createParameter(
                "tolerance",
                SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("NULL::double precision"), SQLDataType.DOUBLE)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_geometricmedian.max_iter</code>.
         */
        val MAX_ITER: Parameter<Int?> =
            Internal.createParameter(
                "max_iter",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("10000"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter
         * <code>public.st_geometricmedian.fail_if_not_converged</code>.
         */
        val FAIL_IF_NOT_CONVERGED: Parameter<Boolean?> =
            Internal.createParameter(
                "fail_if_not_converged",
                SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)),
                true,
                false
            )
    }

    init {
        returnParameter = StGeometricmedian.RETURN_VALUE
        addInParameter(StGeometricmedian.G)
        addInParameter(StGeometricmedian.TOLERANCE)
        addInParameter(StGeometricmedian.MAX_ITER)
        addInParameter(StGeometricmedian.FAIL_IF_NOT_CONVERGED)
    }

    /**
     * Set the <code>g</code> parameter IN value to the routine
     */
    fun setG(value: Geometry?): Unit = setValue(StGeometricmedian.G, value)

    /**
     * Set the <code>g</code> parameter to the function to be used with a {@link
     * org.jooq.Select} statement
     */
    fun setG(field: Field<Geometry?>) {
        setField(StGeometricmedian.G, field)
    }

    /**
     * Set the <code>tolerance</code> parameter IN value to the routine
     */
    fun setTolerance(value: Double?): Unit = setValue(StGeometricmedian.TOLERANCE, value)

    /**
     * Set the <code>tolerance</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setTolerance(field: Field<Double?>) {
        setField(StGeometricmedian.TOLERANCE, field)
    }

    /**
     * Set the <code>max_iter</code> parameter IN value to the routine
     */
    fun setMaxIter(value: Int?): Unit = setValue(StGeometricmedian.MAX_ITER, value)

    /**
     * Set the <code>max_iter</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setMaxIter(field: Field<Int?>) {
        setField(StGeometricmedian.MAX_ITER, field)
    }

    /**
     * Set the <code>fail_if_not_converged</code> parameter IN value to the
     * routine
     */
    fun setFailIfNotConverged(value: Boolean?): Unit = setValue(StGeometricmedian.FAIL_IF_NOT_CONVERGED, value)

    /**
     * Set the <code>fail_if_not_converged</code> parameter to the function to
     * be used with a {@link org.jooq.Select} statement
     */
    fun setFailIfNotConverged(field: Field<Boolean?>) {
        setField(StGeometricmedian.FAIL_IF_NOT_CONVERGED, field)
    }
}
