/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StGeneratepoints2 : AbstractRoutine<Geometry>("st_generatepoints", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_generatepoints.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_generatepoints.area</code>.
         */
        val AREA: Parameter<Geometry?> = Internal.createParameter("area", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_generatepoints.npoints</code>.
         */
        val NPOINTS: Parameter<Int?> = Internal.createParameter("npoints", SQLDataType.INTEGER, false, false)

        /**
         * The parameter <code>public.st_generatepoints.seed</code>.
         */
        val SEED: Parameter<Int?> = Internal.createParameter("seed", SQLDataType.INTEGER, false, false)
    }

    init {
        returnParameter = StGeneratepoints2.RETURN_VALUE
        addInParameter(StGeneratepoints2.AREA)
        addInParameter(StGeneratepoints2.NPOINTS)
        addInParameter(StGeneratepoints2.SEED)
        setOverloaded(true)
    }

    /**
     * Set the <code>area</code> parameter IN value to the routine
     */
    fun setArea(value: Geometry?): Unit = setValue(StGeneratepoints2.AREA, value)

    /**
     * Set the <code>area</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setArea(field: Field<Geometry?>) {
        setField(StGeneratepoints2.AREA, field)
    }

    /**
     * Set the <code>npoints</code> parameter IN value to the routine
     */
    fun setNpoints(value: Int?): Unit = setValue(StGeneratepoints2.NPOINTS, value)

    /**
     * Set the <code>npoints</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setNpoints(field: Field<Int?>) {
        setField(StGeneratepoints2.NPOINTS, field)
    }

    /**
     * Set the <code>seed</code> parameter IN value to the routine
     */
    fun setSeed(value: Int?): Unit = setValue(StGeneratepoints2.SEED, value)

    /**
     * Set the <code>seed</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setSeed(field: Field<Int?>) {
        setField(StGeneratepoints2.SEED, field)
    }
}
