/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StGeohash1 : AbstractRoutine<String>("st_geohash", Public.PUBLIC, DSL.comment(""), SQLDataType.CLOB) {
    companion object {
        /**
         * The parameter <code>public.st_geohash.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false)

        /**
         * The parameter <code>public.st_geohash.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_geohash.maxchars</code>.
         */
        val MAXCHARS: Parameter<Int?> =
            Internal.createParameter(
                "maxchars",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)),
                true,
                false
            )
    }

    init {
        returnParameter = StGeohash1.RETURN_VALUE
        addInParameter(StGeohash1.GEOM)
        addInParameter(StGeohash1.MAXCHARS)
        setOverloaded(true)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StGeohash1.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StGeohash1.GEOM, field)
    }

    /**
     * Set the <code>maxchars</code> parameter IN value to the routine
     */
    fun setMaxchars(value: Int?): Unit = setValue(StGeohash1.MAXCHARS, value)

    /**
     * Set the <code>maxchars</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setMaxchars(field: Field<Int?>) {
        setField(StGeohash1.MAXCHARS, field)
    }
}
