/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StHexagon : AbstractRoutine<Geometry>("st_hexagon", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_hexagon.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_hexagon.size</code>.
         */
        val SIZE: Parameter<Double?> = Internal.createParameter("size", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_hexagon.cell_i</code>.
         */
        val CELL_I: Parameter<Int?> = Internal.createParameter("cell_i", SQLDataType.INTEGER, false, false)

        /**
         * The parameter <code>public.st_hexagon.cell_j</code>.
         */
        val CELL_J: Parameter<Int?> = Internal.createParameter("cell_j", SQLDataType.INTEGER, false, false)

        /**
         * The parameter <code>public.st_hexagon.origin</code>.
         */
        val ORIGIN: Parameter<Geometry?> =
            Internal.createParameter(
                "origin",
                SQLDataType.GEOMETRY.defaultValue(
                    DSL.field(DSL.raw("'010100000000000000000000000000000000000000'::geometry"), SQLDataType.GEOMETRY)
                ),
                true,
                false
            )
    }

    init {
        returnParameter = StHexagon.RETURN_VALUE
        addInParameter(StHexagon.SIZE)
        addInParameter(StHexagon.CELL_I)
        addInParameter(StHexagon.CELL_J)
        addInParameter(StHexagon.ORIGIN)
    }

    /**
     * Set the <code>size</code> parameter IN value to the routine
     */
    fun setSize(value: Double?): Unit = setValue(StHexagon.SIZE, value)

    /**
     * Set the <code>size</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setSize(field: Field<Double?>) {
        setField(StHexagon.SIZE, field)
    }

    /**
     * Set the <code>cell_i</code> parameter IN value to the routine
     */
    fun setCellI(value: Int?): Unit = setValue(StHexagon.CELL_I, value)

    /**
     * Set the <code>cell_i</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setCellI(field: Field<Int?>) {
        setField(StHexagon.CELL_I, field)
    }

    /**
     * Set the <code>cell_j</code> parameter IN value to the routine
     */
    fun setCellJ(value: Int?): Unit = setValue(StHexagon.CELL_J, value)

    /**
     * Set the <code>cell_j</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setCellJ(field: Field<Int?>) {
        setField(StHexagon.CELL_J, field)
    }

    /**
     * Set the <code>origin</code> parameter IN value to the routine
     */
    fun setOrigin(value: Geometry?): Unit = setValue(StHexagon.ORIGIN, value)

    /**
     * Set the <code>origin</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setOrigin(field: Field<Geometry?>) {
        setField(StHexagon.ORIGIN, field)
    }
}
