/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StInversetransformpipeline :
    AbstractRoutine<Geometry>("st_inversetransformpipeline", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter
         * <code>public.st_inversetransformpipeline.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_inversetransformpipeline.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter
         * <code>public.st_inversetransformpipeline.pipeline</code>.
         */
        val PIPELINE: Parameter<String?> = Internal.createParameter("pipeline", SQLDataType.CLOB, false, false)

        /**
         * The parameter
         * <code>public.st_inversetransformpipeline.to_srid</code>.
         */
        val TO_SRID: Parameter<Int?> =
            Internal.createParameter(
                "to_srid",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)),
                true,
                false
            )
    }

    init {
        returnParameter = StInversetransformpipeline.RETURN_VALUE
        addInParameter(StInversetransformpipeline.GEOM)
        addInParameter(StInversetransformpipeline.PIPELINE)
        addInParameter(StInversetransformpipeline.TO_SRID)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StInversetransformpipeline.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StInversetransformpipeline.GEOM, field)
    }

    /**
     * Set the <code>pipeline</code> parameter IN value to the routine
     */
    fun setPipeline(value: String?): Unit = setValue(StInversetransformpipeline.PIPELINE, value)

    /**
     * Set the <code>pipeline</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setPipeline(field: Field<String?>) {
        setField(StInversetransformpipeline.PIPELINE, field)
    }

    /**
     * Set the <code>to_srid</code> parameter IN value to the routine
     */
    fun setToSrid(value: Int?): Unit = setValue(StInversetransformpipeline.TO_SRID, value)

    /**
     * Set the <code>to_srid</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setToSrid(field: Field<Int?>) {
        setField(StInversetransformpipeline.TO_SRID, field)
    }
}
