/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StLargestemptycircle : AbstractRoutine<java.lang.Void>("st_largestemptycircle", Public.PUBLIC, DSL.comment("")) {
    companion object {
        /**
         * The parameter <code>public.st_largestemptycircle.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_largestemptycircle.tolerance</code>.
         */
        val TOLERANCE: Parameter<Double?> =
            Internal.createParameter(
                "tolerance",
                SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.DOUBLE)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_largestemptycircle.boundary</code>.
         */
        val BOUNDARY: Parameter<Geometry?> =
            Internal.createParameter(
                "boundary",
                SQLDataType.GEOMETRY.defaultValue(
                    DSL.field(DSL.raw("'0101000000000000000000F87F000000000000F87F'::geometry"), SQLDataType.GEOMETRY)
                ),
                true,
                false
            )

        /**
         * The parameter <code>public.st_largestemptycircle.center</code>.
         */
        val CENTER: Parameter<Geometry?> = Internal.createParameter("center", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_largestemptycircle.nearest</code>.
         */
        val NEAREST: Parameter<Geometry?> = Internal.createParameter("nearest", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_largestemptycircle.radius</code>.
         */
        val RADIUS: Parameter<Double?> = Internal.createParameter("radius", SQLDataType.DOUBLE, false, false)
    }

    init {
        addInParameter(StLargestemptycircle.GEOM)
        addInParameter(StLargestemptycircle.TOLERANCE)
        addInParameter(StLargestemptycircle.BOUNDARY)
        addOutParameter(StLargestemptycircle.CENTER)
        addOutParameter(StLargestemptycircle.NEAREST)
        addOutParameter(StLargestemptycircle.RADIUS)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StLargestemptycircle.GEOM, value)

    /**
     * Set the <code>tolerance</code> parameter IN value to the routine
     */
    fun setTolerance(value: Double?): Unit = setValue(StLargestemptycircle.TOLERANCE, value)

    /**
     * Set the <code>boundary</code> parameter IN value to the routine
     */
    fun setBoundary(value: Geometry?): Unit = setValue(StLargestemptycircle.BOUNDARY, value)

    /**
     * Get the <code>center</code> parameter OUT value from the routine
     */
    fun getCenter(): Geometry? = get(StLargestemptycircle.CENTER)

    /**
     * Get the <code>nearest</code> parameter OUT value from the routine
     */
    fun getNearest(): Geometry? = get(StLargestemptycircle.NEAREST)

    /**
     * Get the <code>radius</code> parameter OUT value from the routine
     */
    fun getRadius(): Double? = get(StLargestemptycircle.RADIUS)
}
