/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StLineextend : AbstractRoutine<Geometry>("st_lineextend", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_lineextend.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_lineextend.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_lineextend.distance_forward</code>.
         */
        val DISTANCE_FORWARD: Parameter<Double?> = Internal.createParameter("distance_forward", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_lineextend.distance_backward</code>.
         */
        val DISTANCE_BACKWARD: Parameter<Double?> =
            Internal.createParameter(
                "distance_backward",
                SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.DOUBLE)),
                true,
                false
            )
    }

    init {
        returnParameter = StLineextend.RETURN_VALUE
        addInParameter(StLineextend.GEOM)
        addInParameter(StLineextend.DISTANCE_FORWARD)
        addInParameter(StLineextend.DISTANCE_BACKWARD)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StLineextend.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StLineextend.GEOM, field)
    }

    /**
     * Set the <code>distance_forward</code> parameter IN value to the routine
     */
    fun setDistanceForward(value: Double?): Unit = setValue(StLineextend.DISTANCE_FORWARD, value)

    /**
     * Set the <code>distance_forward</code> parameter to the function to be
     * used with a {@link org.jooq.Select} statement
     */
    fun setDistanceForward(field: Field<Double?>) {
        setField(StLineextend.DISTANCE_FORWARD, field)
    }

    /**
     * Set the <code>distance_backward</code> parameter IN value to the routine
     */
    fun setDistanceBackward(value: Double?): Unit = setValue(StLineextend.DISTANCE_BACKWARD, value)

    /**
     * Set the <code>distance_backward</code> parameter to the function to be
     * used with a {@link org.jooq.Select} statement
     */
    fun setDistanceBackward(field: Field<Double?>) {
        setField(StLineextend.DISTANCE_BACKWARD, field)
    }
}
