/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StLocatebetween : AbstractRoutine<Geometry>("st_locatebetween", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_locatebetween.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_locatebetween.geometry</code>.
         */
        val GEOMETRY: Parameter<Geometry?> = Internal.createParameter("geometry", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_locatebetween.frommeasure</code>.
         */
        val FROMMEASURE: Parameter<Double?> = Internal.createParameter("frommeasure", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_locatebetween.tomeasure</code>.
         */
        val TOMEASURE: Parameter<Double?> = Internal.createParameter("tomeasure", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_locatebetween.leftrightoffset</code>.
         */
        val LEFTRIGHTOFFSET: Parameter<Double?> =
            Internal.createParameter(
                "leftrightoffset",
                SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.DOUBLE)),
                true,
                false
            )
    }

    init {
        returnParameter = StLocatebetween.RETURN_VALUE
        addInParameter(StLocatebetween.GEOMETRY)
        addInParameter(StLocatebetween.FROMMEASURE)
        addInParameter(StLocatebetween.TOMEASURE)
        addInParameter(StLocatebetween.LEFTRIGHTOFFSET)
    }

    /**
     * Set the <code>geometry</code> parameter IN value to the routine
     */
    fun setGeometry(value: Geometry?): Unit = setValue(StLocatebetween.GEOMETRY, value)

    /**
     * Set the <code>geometry</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeometry(field: Field<Geometry?>) {
        setField(StLocatebetween.GEOMETRY, field)
    }

    /**
     * Set the <code>frommeasure</code> parameter IN value to the routine
     */
    fun setFrommeasure(value: Double?): Unit = setValue(StLocatebetween.FROMMEASURE, value)

    /**
     * Set the <code>frommeasure</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setFrommeasure(field: Field<Double?>) {
        setField(StLocatebetween.FROMMEASURE, field)
    }

    /**
     * Set the <code>tomeasure</code> parameter IN value to the routine
     */
    fun setTomeasure(value: Double?): Unit = setValue(StLocatebetween.TOMEASURE, value)

    /**
     * Set the <code>tomeasure</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setTomeasure(field: Field<Double?>) {
        setField(StLocatebetween.TOMEASURE, field)
    }

    /**
     * Set the <code>leftrightoffset</code> parameter IN value to the routine
     */
    fun setLeftrightoffset(value: Double?): Unit = setValue(StLocatebetween.LEFTRIGHTOFFSET, value)

    /**
     * Set the <code>leftrightoffset</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setLeftrightoffset(field: Field<Double?>) {
        setField(StLocatebetween.LEFTRIGHTOFFSET, field)
    }
}
