/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StLocatebetweenelevations :
    AbstractRoutine<Geometry>("st_locatebetweenelevations", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter
         * <code>public.st_locatebetweenelevations.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter
         * <code>public.st_locatebetweenelevations.geometry</code>.
         */
        val GEOMETRY: Parameter<Geometry?> = Internal.createParameter("geometry", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter
         * <code>public.st_locatebetweenelevations.fromelevation</code>.
         */
        val FROMELEVATION: Parameter<Double?> = Internal.createParameter("fromelevation", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter
         * <code>public.st_locatebetweenelevations.toelevation</code>.
         */
        val TOELEVATION: Parameter<Double?> = Internal.createParameter("toelevation", SQLDataType.DOUBLE, false, false)
    }

    init {
        returnParameter = StLocatebetweenelevations.RETURN_VALUE
        addInParameter(StLocatebetweenelevations.GEOMETRY)
        addInParameter(StLocatebetweenelevations.FROMELEVATION)
        addInParameter(StLocatebetweenelevations.TOELEVATION)
    }

    /**
     * Set the <code>geometry</code> parameter IN value to the routine
     */
    fun setGeometry(value: Geometry?): Unit = setValue(StLocatebetweenelevations.GEOMETRY, value)

    /**
     * Set the <code>geometry</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeometry(field: Field<Geometry?>) {
        setField(StLocatebetweenelevations.GEOMETRY, field)
    }

    /**
     * Set the <code>fromelevation</code> parameter IN value to the routine
     */
    fun setFromelevation(value: Double?): Unit = setValue(StLocatebetweenelevations.FROMELEVATION, value)

    /**
     * Set the <code>fromelevation</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setFromelevation(field: Field<Double?>) {
        setField(StLocatebetweenelevations.FROMELEVATION, field)
    }

    /**
     * Set the <code>toelevation</code> parameter IN value to the routine
     */
    fun setToelevation(value: Double?): Unit = setValue(StLocatebetweenelevations.TOELEVATION, value)

    /**
     * Set the <code>toelevation</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setToelevation(field: Field<Double?>) {
        setField(StLocatebetweenelevations.TOELEVATION, field)
    }
}
