/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StMakeenvelope : AbstractRoutine<Geometry>("st_makeenvelope", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_makeenvelope.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_makeenvelope._1</code>.
         */
        val _1: Parameter<Double?> = Internal.createParameter("_1", SQLDataType.DOUBLE, false, true)

        /**
         * The parameter <code>public.st_makeenvelope._2</code>.
         */
        val _2: Parameter<Double?> = Internal.createParameter("_2", SQLDataType.DOUBLE, false, true)

        /**
         * The parameter <code>public.st_makeenvelope._3</code>.
         */
        val _3: Parameter<Double?> = Internal.createParameter("_3", SQLDataType.DOUBLE, false, true)

        /**
         * The parameter <code>public.st_makeenvelope._4</code>.
         */
        val _4: Parameter<Double?> = Internal.createParameter("_4", SQLDataType.DOUBLE, false, true)

        /**
         * The parameter <code>public.st_makeenvelope._5</code>.
         */
        val _5: Parameter<Int?> =
            Internal.createParameter(
                "_5",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)),
                true,
                true
            )
    }

    init {
        returnParameter = StMakeenvelope.RETURN_VALUE
        addInParameter(StMakeenvelope._1)
        addInParameter(StMakeenvelope._2)
        addInParameter(StMakeenvelope._3)
        addInParameter(StMakeenvelope._4)
        addInParameter(StMakeenvelope._5)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Double?): Unit = setValue(StMakeenvelope._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Double?>) {
        setField(StMakeenvelope._1, field)
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    fun set__2(value: Double?): Unit = setValue(StMakeenvelope._2, value)

    /**
     * Set the <code>_2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__2(field: Field<Double?>) {
        setField(StMakeenvelope._2, field)
    }

    /**
     * Set the <code>_3</code> parameter IN value to the routine
     */
    fun set__3(value: Double?): Unit = setValue(StMakeenvelope._3, value)

    /**
     * Set the <code>_3</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__3(field: Field<Double?>) {
        setField(StMakeenvelope._3, field)
    }

    /**
     * Set the <code>_4</code> parameter IN value to the routine
     */
    fun set__4(value: Double?): Unit = setValue(StMakeenvelope._4, value)

    /**
     * Set the <code>_4</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__4(field: Field<Double?>) {
        setField(StMakeenvelope._4, field)
    }

    /**
     * Set the <code>_5</code> parameter IN value to the routine
     */
    fun set__5(value: Int?): Unit = setValue(StMakeenvelope._5, value)

    /**
     * Set the <code>_5</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__5(field: Field<Int?>) {
        setField(StMakeenvelope._5, field)
    }
}
