/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StMinimumboundingradius : AbstractRoutine<java.lang.Void>("st_minimumboundingradius", Public.PUBLIC, DSL.comment("")) {
    companion object {
        /**
         * The parameter <code>public.st_minimumboundingradius._1</code>.
         */
        val _1: Parameter<Geometry?> = Internal.createParameter("_1", SQLDataType.GEOMETRY, false, true)

        /**
         * The parameter <code>public.st_minimumboundingradius.center</code>.
         */
        val CENTER: Parameter<Geometry?> = Internal.createParameter("center", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_minimumboundingradius.radius</code>.
         */
        val RADIUS: Parameter<Double?> = Internal.createParameter("radius", SQLDataType.DOUBLE, false, false)
    }

    init {
        addInParameter(StMinimumboundingradius._1)
        addOutParameter(StMinimumboundingradius.CENTER)
        addOutParameter(StMinimumboundingradius.RADIUS)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Geometry?): Unit = setValue(StMinimumboundingradius._1, value)

    /**
     * Get the <code>center</code> parameter OUT value from the routine
     */
    fun getCenter(): Geometry? = get(StMinimumboundingradius.CENTER)

    /**
     * Get the <code>radius</code> parameter OUT value from the routine
     */
    fun getRadius(): Double? = get(StMinimumboundingradius.RADIUS)
}
