/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StMinimumboundingcircle :
    AbstractRoutine<Geometry>("st_minimumboundingcircle", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter
         * <code>public.st_minimumboundingcircle.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_minimumboundingcircle.inputgeom</code>.
         */
        val INPUTGEOM: Parameter<Geometry?> = Internal.createParameter("inputgeom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter
         * <code>public.st_minimumboundingcircle.segs_per_quarter</code>.
         */
        val SEGS_PER_QUARTER: Parameter<Int?> =
            Internal.createParameter(
                "segs_per_quarter",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("48"), SQLDataType.INTEGER)),
                true,
                false
            )
    }

    init {
        returnParameter = StMinimumboundingcircle.RETURN_VALUE
        addInParameter(StMinimumboundingcircle.INPUTGEOM)
        addInParameter(StMinimumboundingcircle.SEGS_PER_QUARTER)
    }

    /**
     * Set the <code>inputgeom</code> parameter IN value to the routine
     */
    fun setInputgeom(value: Geometry?): Unit = setValue(StMinimumboundingcircle.INPUTGEOM, value)

    /**
     * Set the <code>inputgeom</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setInputgeom(field: Field<Geometry?>) {
        setField(StMinimumboundingcircle.INPUTGEOM, field)
    }

    /**
     * Set the <code>segs_per_quarter</code> parameter IN value to the routine
     */
    fun setSegsPerQuarter(value: Int?): Unit = setValue(StMinimumboundingcircle.SEGS_PER_QUARTER, value)

    /**
     * Set the <code>segs_per_quarter</code> parameter to the function to be
     * used with a {@link org.jooq.Select} statement
     */
    fun setSegsPerQuarter(field: Field<Int?>) {
        setField(StMinimumboundingcircle.SEGS_PER_QUARTER, field)
    }
}
