/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StMultipointfromwkb2 : AbstractRoutine<Geometry>("st_multipointfromwkb", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_multipointfromwkb.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_multipointfromwkb._1</code>.
         */
        val _1: Parameter<ByteArray?> = Internal.createParameter("_1", SQLDataType.BLOB, false, true)
    }

    init {
        returnParameter = StMultipointfromwkb2.RETURN_VALUE
        addInParameter(StMultipointfromwkb2._1)
        setOverloaded(true)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: ByteArray?): Unit = setValue(StMultipointfromwkb2._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<ByteArray?>) {
        setField(StMultipointfromwkb2._1, field)
    }
}
