/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StNode : AbstractRoutine<Geometry>("st_node", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_node.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_node.g</code>.
         */
        val G: Parameter<Geometry?> = Internal.createParameter("g", SQLDataType.GEOMETRY, false, false)
    }

    init {
        returnParameter = StNode.RETURN_VALUE
        addInParameter(StNode.G)
    }

    /**
     * Set the <code>g</code> parameter IN value to the routine
     */
    fun setG(value: Geometry?): Unit = setValue(StNode.G, value)

    /**
     * Set the <code>g</code> parameter to the function to be used with a {@link
     * org.jooq.Select} statement
     */
    fun setG(field: Field<Geometry?>) {
        setField(StNode.G, field)
    }
}
