/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StNumcurves : AbstractRoutine<Int>("st_numcurves", Public.PUBLIC, DSL.comment(""), SQLDataType.INTEGER) {
    companion object {
        /**
         * The parameter <code>public.st_numcurves.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Int?> = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false)

        /**
         * The parameter <code>public.st_numcurves.geometry</code>.
         */
        val GEOMETRY: Parameter<Geometry?> = Internal.createParameter("geometry", SQLDataType.GEOMETRY, false, false)
    }

    init {
        returnParameter = StNumcurves.RETURN_VALUE
        addInParameter(StNumcurves.GEOMETRY)
    }

    /**
     * Set the <code>geometry</code> parameter IN value to the routine
     */
    fun setGeometry(value: Geometry?): Unit = setValue(StNumcurves.GEOMETRY, value)

    /**
     * Set the <code>geometry</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeometry(field: Field<Geometry?>) {
        setField(StNumcurves.GEOMETRY, field)
    }
}
