/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StPointzm : AbstractRoutine<Geometry>("st_pointzm", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_pointzm.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_pointzm.xcoordinate</code>.
         */
        val XCOORDINATE: Parameter<Double?> = Internal.createParameter("xcoordinate", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_pointzm.ycoordinate</code>.
         */
        val YCOORDINATE: Parameter<Double?> = Internal.createParameter("ycoordinate", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_pointzm.zcoordinate</code>.
         */
        val ZCOORDINATE: Parameter<Double?> = Internal.createParameter("zcoordinate", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_pointzm.mcoordinate</code>.
         */
        val MCOORDINATE: Parameter<Double?> = Internal.createParameter("mcoordinate", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_pointzm.srid</code>.
         */
        val SRID: Parameter<Int?> =
            Internal.createParameter(
                "srid",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)),
                true,
                false
            )
    }

    init {
        returnParameter = StPointzm.RETURN_VALUE
        addInParameter(StPointzm.XCOORDINATE)
        addInParameter(StPointzm.YCOORDINATE)
        addInParameter(StPointzm.ZCOORDINATE)
        addInParameter(StPointzm.MCOORDINATE)
        addInParameter(StPointzm.SRID)
    }

    /**
     * Set the <code>xcoordinate</code> parameter IN value to the routine
     */
    fun setXcoordinate(value: Double?): Unit = setValue(StPointzm.XCOORDINATE, value)

    /**
     * Set the <code>xcoordinate</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setXcoordinate(field: Field<Double?>) {
        setField(StPointzm.XCOORDINATE, field)
    }

    /**
     * Set the <code>ycoordinate</code> parameter IN value to the routine
     */
    fun setYcoordinate(value: Double?): Unit = setValue(StPointzm.YCOORDINATE, value)

    /**
     * Set the <code>ycoordinate</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setYcoordinate(field: Field<Double?>) {
        setField(StPointzm.YCOORDINATE, field)
    }

    /**
     * Set the <code>zcoordinate</code> parameter IN value to the routine
     */
    fun setZcoordinate(value: Double?): Unit = setValue(StPointzm.ZCOORDINATE, value)

    /**
     * Set the <code>zcoordinate</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setZcoordinate(field: Field<Double?>) {
        setField(StPointzm.ZCOORDINATE, field)
    }

    /**
     * Set the <code>mcoordinate</code> parameter IN value to the routine
     */
    fun setMcoordinate(value: Double?): Unit = setValue(StPointzm.MCOORDINATE, value)

    /**
     * Set the <code>mcoordinate</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setMcoordinate(field: Field<Double?>) {
        setField(StPointzm.MCOORDINATE, field)
    }

    /**
     * Set the <code>srid</code> parameter IN value to the routine
     */
    fun setSrid(value: Int?): Unit = setValue(StPointzm.SRID, value)

    /**
     * Set the <code>srid</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setSrid(field: Field<Int?>) {
        setField(StPointzm.SRID, field)
    }
}
