/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StProject2 : AbstractRoutine<Geometry>("st_project", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_project.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_project.geom1</code>.
         */
        val GEOM1: Parameter<Geometry?> = Internal.createParameter("geom1", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_project.geom2</code>.
         */
        val GEOM2: Parameter<Geometry?> = Internal.createParameter("geom2", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_project.distance</code>.
         */
        val DISTANCE: Parameter<Double?> = Internal.createParameter("distance", SQLDataType.DOUBLE, false, false)
    }

    init {
        returnParameter = StProject2.RETURN_VALUE
        addInParameter(StProject2.GEOM1)
        addInParameter(StProject2.GEOM2)
        addInParameter(StProject2.DISTANCE)
        setOverloaded(true)
    }

    /**
     * Set the <code>geom1</code> parameter IN value to the routine
     */
    fun setGeom1(value: Geometry?): Unit = setValue(StProject2.GEOM1, value)

    /**
     * Set the <code>geom1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom1(field: Field<Geometry?>) {
        setField(StProject2.GEOM1, field)
    }

    /**
     * Set the <code>geom2</code> parameter IN value to the routine
     */
    fun setGeom2(value: Geometry?): Unit = setValue(StProject2.GEOM2, value)

    /**
     * Set the <code>geom2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom2(field: Field<Geometry?>) {
        setField(StProject2.GEOM2, field)
    }

    /**
     * Set the <code>distance</code> parameter IN value to the routine
     */
    fun setDistance(value: Double?): Unit = setValue(StProject2.DISTANCE, value)

    /**
     * Set the <code>distance</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setDistance(field: Field<Double?>) {
        setField(StProject2.DISTANCE, field)
    }
}
