/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

@Deprecated(
    message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
)
@Suppress("warnings")
open class StProject4 :
    AbstractRoutine<Any>("st_project", Public.PUBLIC, DSL.comment(""), DefaultDataType.getDefaultDataType("\"public\".\"geography\"")) {
    companion object {
        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val RETURN_VALUE: Parameter<Any?> =
            Internal.createParameter(
                "RETURN_VALUE",
                DefaultDataType.getDefaultDataType("\"public\".\"geography\""),
                false,
                false
            )

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val GEOG_FROM: Parameter<Any?> =
            Internal.createParameter(
                "geog_from",
                DefaultDataType.getDefaultDataType("\"public\".\"geography\""),
                false,
                false
            )

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val GEOG_TO: Parameter<Any?> =
            Internal.createParameter(
                "geog_to",
                DefaultDataType.getDefaultDataType("\"public\".\"geography\""),
                false,
                false
            )

        /**
         * The parameter <code>public.st_project.distance</code>.
         */
        val DISTANCE: Parameter<Double?> = Internal.createParameter("distance", SQLDataType.DOUBLE, false, false)
    }

    init {
        returnParameter = StProject4.RETURN_VALUE
        addInParameter(StProject4.GEOG_FROM)
        addInParameter(StProject4.GEOG_TO)
        addInParameter(StProject4.DISTANCE)
        setOverloaded(true)
    }

    /**
     * Set the <code>geog_from</code> parameter IN value to the routine
     */
    fun setGeogFrom(value: Any?): Unit = setValue(StProject4.GEOG_FROM, value)

    /**
     * Set the <code>geog_from</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setGeogFrom(field: Field<Any?>) {
        setField(StProject4.GEOG_FROM, field)
    }

    /**
     * Set the <code>geog_to</code> parameter IN value to the routine
     */
    fun setGeogTo(value: Any?): Unit = setValue(StProject4.GEOG_TO, value)

    /**
     * Set the <code>geog_to</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeogTo(field: Field<Any?>) {
        setField(StProject4.GEOG_TO, field)
    }

    /**
     * Set the <code>distance</code> parameter IN value to the routine
     */
    fun setDistance(value: Double?): Unit = setValue(StProject4.DISTANCE, value)

    /**
     * Set the <code>distance</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setDistance(field: Field<Double?>) {
        setField(StProject4.DISTANCE, field)
    }
}
