/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

@Deprecated(
    message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
)
@Suppress("warnings")
open class StProject3 :
    AbstractRoutine<Any>("st_project", Public.PUBLIC, DSL.comment(""), DefaultDataType.getDefaultDataType("\"public\".\"geography\"")) {
    companion object {
        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val RETURN_VALUE: Parameter<Any?> =
            Internal.createParameter(
                "RETURN_VALUE",
                DefaultDataType.getDefaultDataType("\"public\".\"geography\""),
                false,
                false
            )

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val GEOG: Parameter<Any?> =
            Internal.createParameter(
                "geog",
                DefaultDataType.getDefaultDataType("\"public\".\"geography\""),
                false,
                false
            )

        /**
         * The parameter <code>public.st_project.distance</code>.
         */
        val DISTANCE: Parameter<Double?> = Internal.createParameter("distance", SQLDataType.DOUBLE, false, false)

        /**
         * The parameter <code>public.st_project.azimuth</code>.
         */
        val AZIMUTH: Parameter<Double?> = Internal.createParameter("azimuth", SQLDataType.DOUBLE, false, false)
    }

    init {
        returnParameter = StProject3.RETURN_VALUE
        addInParameter(StProject3.GEOG)
        addInParameter(StProject3.DISTANCE)
        addInParameter(StProject3.AZIMUTH)
        setOverloaded(true)
    }

    /**
     * Set the <code>geog</code> parameter IN value to the routine
     */
    fun setGeog(value: Any?): Unit = setValue(StProject3.GEOG, value)

    /**
     * Set the <code>geog</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeog(field: Field<Any?>) {
        setField(StProject3.GEOG, field)
    }

    /**
     * Set the <code>distance</code> parameter IN value to the routine
     */
    fun setDistance(value: Double?): Unit = setValue(StProject3.DISTANCE, value)

    /**
     * Set the <code>distance</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setDistance(field: Field<Double?>) {
        setField(StProject3.DISTANCE, field)
    }

    /**
     * Set the <code>azimuth</code> parameter IN value to the routine
     */
    fun setAzimuth(value: Double?): Unit = setValue(StProject3.AZIMUTH, value)

    /**
     * Set the <code>azimuth</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setAzimuth(field: Field<Double?>) {
        setField(StProject3.AZIMUTH, field)
    }
}
