/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StQuantizecoordinates :
    AbstractRoutine<Geometry>("st_quantizecoordinates", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter
         * <code>public.st_quantizecoordinates.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_quantizecoordinates.g</code>.
         */
        val G: Parameter<Geometry?> = Internal.createParameter("g", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_quantizecoordinates.prec_x</code>.
         */
        val PREC_X: Parameter<Int?> = Internal.createParameter("prec_x", SQLDataType.INTEGER, false, false)

        /**
         * The parameter <code>public.st_quantizecoordinates.prec_y</code>.
         */
        val PREC_Y: Parameter<Int?> =
            Internal.createParameter(
                "prec_y",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL::integer"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_quantizecoordinates.prec_z</code>.
         */
        val PREC_Z: Parameter<Int?> =
            Internal.createParameter(
                "prec_z",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL::integer"), SQLDataType.INTEGER)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_quantizecoordinates.prec_m</code>.
         */
        val PREC_M: Parameter<Int?> =
            Internal.createParameter(
                "prec_m",
                SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL::integer"), SQLDataType.INTEGER)),
                true,
                false
            )
    }

    init {
        returnParameter = StQuantizecoordinates.RETURN_VALUE
        addInParameter(StQuantizecoordinates.G)
        addInParameter(StQuantizecoordinates.PREC_X)
        addInParameter(StQuantizecoordinates.PREC_Y)
        addInParameter(StQuantizecoordinates.PREC_Z)
        addInParameter(StQuantizecoordinates.PREC_M)
    }

    /**
     * Set the <code>g</code> parameter IN value to the routine
     */
    fun setG(value: Geometry?): Unit = setValue(StQuantizecoordinates.G, value)

    /**
     * Set the <code>g</code> parameter to the function to be used with a {@link
     * org.jooq.Select} statement
     */
    fun setG(field: Field<Geometry?>) {
        setField(StQuantizecoordinates.G, field)
    }

    /**
     * Set the <code>prec_x</code> parameter IN value to the routine
     */
    fun setPrecX(value: Int?): Unit = setValue(StQuantizecoordinates.PREC_X, value)

    /**
     * Set the <code>prec_x</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setPrecX(field: Field<Int?>) {
        setField(StQuantizecoordinates.PREC_X, field)
    }

    /**
     * Set the <code>prec_y</code> parameter IN value to the routine
     */
    fun setPrecY(value: Int?): Unit = setValue(StQuantizecoordinates.PREC_Y, value)

    /**
     * Set the <code>prec_y</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setPrecY(field: Field<Int?>) {
        setField(StQuantizecoordinates.PREC_Y, field)
    }

    /**
     * Set the <code>prec_z</code> parameter IN value to the routine
     */
    fun setPrecZ(value: Int?): Unit = setValue(StQuantizecoordinates.PREC_Z, value)

    /**
     * Set the <code>prec_z</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setPrecZ(field: Field<Int?>) {
        setField(StQuantizecoordinates.PREC_Z, field)
    }

    /**
     * Set the <code>prec_m</code> parameter IN value to the routine
     */
    fun setPrecM(value: Int?): Unit = setValue(StQuantizecoordinates.PREC_M, value)

    /**
     * Set the <code>prec_m</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setPrecM(field: Field<Int?>) {
        setField(StQuantizecoordinates.PREC_M, field)
    }
}
