/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StReduceprecision : AbstractRoutine<Geometry>("st_reduceprecision", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_reduceprecision.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_reduceprecision.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_reduceprecision.gridsize</code>.
         */
        val GRIDSIZE: Parameter<Double?> = Internal.createParameter("gridsize", SQLDataType.DOUBLE, false, false)
    }

    init {
        returnParameter = StReduceprecision.RETURN_VALUE
        addInParameter(StReduceprecision.GEOM)
        addInParameter(StReduceprecision.GRIDSIZE)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StReduceprecision.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StReduceprecision.GEOM, field)
    }

    /**
     * Set the <code>gridsize</code> parameter IN value to the routine
     */
    fun setGridsize(value: Double?): Unit = setValue(StReduceprecision.GRIDSIZE, value)

    /**
     * Set the <code>gridsize</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGridsize(field: Field<Double?>) {
        setField(StReduceprecision.GRIDSIZE, field)
    }
}
