/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StSetsrid1 : AbstractRoutine<Geometry>("st_setsrid", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_setsrid.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_setsrid.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_setsrid.srid</code>.
         */
        val SRID: Parameter<Int?> = Internal.createParameter("srid", SQLDataType.INTEGER, false, false)
    }

    init {
        returnParameter = StSetsrid1.RETURN_VALUE
        addInParameter(StSetsrid1.GEOM)
        addInParameter(StSetsrid1.SRID)
        setOverloaded(true)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StSetsrid1.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StSetsrid1.GEOM, field)
    }

    /**
     * Set the <code>srid</code> parameter IN value to the routine
     */
    fun setSrid(value: Int?): Unit = setValue(StSetsrid1.SRID, value)

    /**
     * Set the <code>srid</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setSrid(field: Field<Int?>) {
        setField(StSetsrid1.SRID, field)
    }
}
