/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

@Deprecated(
    message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
)
@Suppress("warnings")
open class StSegmentize2 :
    AbstractRoutine<Any>("st_segmentize", Public.PUBLIC, DSL.comment(""), DefaultDataType.getDefaultDataType("\"public\".\"geography\"")) {
    companion object {
        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val RETURN_VALUE: Parameter<Any?> =
            Internal.createParameter(
                "RETURN_VALUE",
                DefaultDataType.getDefaultDataType("\"public\".\"geography\""),
                false,
                false
            )

        @Deprecated(
            message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration."
        )
        val GEOG: Parameter<Any?> =
            Internal.createParameter(
                "geog",
                DefaultDataType.getDefaultDataType("\"public\".\"geography\""),
                false,
                false
            )

        /**
         * The parameter <code>public.st_segmentize.max_segment_length</code>.
         */
        val MAX_SEGMENT_LENGTH: Parameter<Double?> = Internal.createParameter("max_segment_length", SQLDataType.DOUBLE, false, false)
    }

    init {
        returnParameter = StSegmentize2.RETURN_VALUE
        addInParameter(StSegmentize2.GEOG)
        addInParameter(StSegmentize2.MAX_SEGMENT_LENGTH)
        setOverloaded(true)
    }

    /**
     * Set the <code>geog</code> parameter IN value to the routine
     */
    fun setGeog(value: Any?): Unit = setValue(StSegmentize2.GEOG, value)

    /**
     * Set the <code>geog</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeog(field: Field<Any?>) {
        setField(StSegmentize2.GEOG, field)
    }

    /**
     * Set the <code>max_segment_length</code> parameter IN value to the routine
     */
    fun setMaxSegmentLength(value: Double?): Unit = setValue(StSegmentize2.MAX_SEGMENT_LENGTH, value)

    /**
     * Set the <code>max_segment_length</code> parameter to the function to be
     * used with a {@link org.jooq.Select} statement
     */
    fun setMaxSegmentLength(field: Field<Double?>) {
        setField(StSegmentize2.MAX_SEGMENT_LENGTH, field)
    }
}
