/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StSrid1 : AbstractRoutine<Int>("st_srid", Public.PUBLIC, DSL.comment(""), SQLDataType.INTEGER) {
    companion object {
        /**
         * The parameter <code>public.st_srid.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Int?> = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false)

        /**
         * The parameter <code>public.st_srid.geom</code>.
         */
        val GEOM: Parameter<Geometry?> = Internal.createParameter("geom", SQLDataType.GEOMETRY, false, false)
    }

    init {
        returnParameter = StSrid1.RETURN_VALUE
        addInParameter(StSrid1.GEOM)
        setOverloaded(true)
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    fun setGeom(value: Geometry?): Unit = setValue(StSrid1.GEOM, value)

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setGeom(field: Field<Geometry?>) {
        setField(StSrid1.GEOM, field)
    }
}
