/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StVoronoilines : AbstractRoutine<Geometry>("st_voronoilines", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_voronoilines.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_voronoilines.g1</code>.
         */
        val G1: Parameter<Geometry?> = Internal.createParameter("g1", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_voronoilines.tolerance</code>.
         */
        val TOLERANCE: Parameter<Double?> =
            Internal.createParameter(
                "tolerance",
                SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.DOUBLE)),
                true,
                false
            )

        /**
         * The parameter <code>public.st_voronoilines.extend_to</code>.
         */
        val EXTEND_TO: Parameter<Geometry?> =
            Internal.createParameter(
                "extend_to",
                SQLDataType.GEOMETRY.defaultValue(DSL.field(DSL.raw("NULL::geometry"), SQLDataType.GEOMETRY)),
                true,
                false
            )
    }

    init {
        returnParameter = StVoronoilines.RETURN_VALUE
        addInParameter(StVoronoilines.G1)
        addInParameter(StVoronoilines.TOLERANCE)
        addInParameter(StVoronoilines.EXTEND_TO)
    }

    /**
     * Set the <code>g1</code> parameter IN value to the routine
     */
    fun setG1(value: Geometry?): Unit = setValue(StVoronoilines.G1, value)

    /**
     * Set the <code>g1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setG1(field: Field<Geometry?>) {
        setField(StVoronoilines.G1, field)
    }

    /**
     * Set the <code>tolerance</code> parameter IN value to the routine
     */
    fun setTolerance(value: Double?): Unit = setValue(StVoronoilines.TOLERANCE, value)

    /**
     * Set the <code>tolerance</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setTolerance(field: Field<Double?>) {
        setField(StVoronoilines.TOLERANCE, field)
    }

    /**
     * Set the <code>extend_to</code> parameter IN value to the routine
     */
    fun setExtendTo(value: Geometry?): Unit = setValue(StVoronoilines.EXTEND_TO, value)

    /**
     * Set the <code>extend_to</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setExtendTo(field: Field<Geometry?>) {
        setField(StVoronoilines.EXTEND_TO, field)
    }
}
