/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.routines

import org.jooq.Field
import org.jooq.Geometry
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType

import yayauheny.by.Public

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StWkbtosql : AbstractRoutine<Geometry>("st_wkbtosql", Public.PUBLIC, DSL.comment(""), SQLDataType.GEOMETRY) {
    companion object {
        /**
         * The parameter <code>public.st_wkbtosql.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Geometry?> = Internal.createParameter("RETURN_VALUE", SQLDataType.GEOMETRY, false, false)

        /**
         * The parameter <code>public.st_wkbtosql.wkb</code>.
         */
        val WKB: Parameter<ByteArray?> = Internal.createParameter("wkb", SQLDataType.BLOB, false, false)
    }

    init {
        returnParameter = StWkbtosql.RETURN_VALUE
        addInParameter(StWkbtosql.WKB)
    }

    /**
     * Set the <code>wkb</code> parameter IN value to the routine
     */
    fun setWkb(value: ByteArray?): Unit = setValue(StWkbtosql.WKB, value)

    /**
     * Set the <code>wkb</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setWkb(field: Field<ByteArray?>) {
        setField(StWkbtosql.WKB, field)
    }
}
