/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.tables


import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Geometry
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import yayauheny.by.Public
import yayauheny.by.tables.records.PostgisSrsSearchRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class PostgisSrsSearch(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PostgisSrsSearchRecord>?,
    parentPath: InverseForeignKey<out Record, PostgisSrsSearchRecord>?,
    aliased: Table<PostgisSrsSearchRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PostgisSrsSearchRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.function(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.postgis_srs_search</code>
         */
        val POSTGIS_SRS_SEARCH: PostgisSrsSearch = PostgisSrsSearch()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PostgisSrsSearchRecord> = PostgisSrsSearchRecord::class.java

    /**
     * The column <code>public.postgis_srs_search.auth_name</code>.
     */
    val AUTH_NAME: TableField<PostgisSrsSearchRecord, String?> = createField(DSL.name("auth_name"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.postgis_srs_search.auth_srid</code>.
     */
    val AUTH_SRID: TableField<PostgisSrsSearchRecord, String?> = createField(DSL.name("auth_srid"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.postgis_srs_search.srname</code>.
     */
    val SRNAME: TableField<PostgisSrsSearchRecord, String?> = createField(DSL.name("srname"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.postgis_srs_search.srtext</code>.
     */
    val SRTEXT: TableField<PostgisSrsSearchRecord, String?> = createField(DSL.name("srtext"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.postgis_srs_search.proj4text</code>.
     */
    val PROJ4TEXT: TableField<PostgisSrsSearchRecord, String?> = createField(DSL.name("proj4text"), SQLDataType.CLOB, this, "")
    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val POINT_SW: TableField<PostgisSrsSearchRecord, Any?> = createField(DSL.name("point_sw"), DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "")
    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val POINT_NE: TableField<PostgisSrsSearchRecord, Any?> = createField(DSL.name("point_ne"), DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "")

    private constructor(alias: Name, aliased: Table<PostgisSrsSearchRecord>?): this(alias, null, null, null, aliased, arrayOf(
        DSL.value(null, SQLDataType.GEOMETRY),
        DSL.value(null, SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("'EPSG'::text"), SQLDataType.CLOB)))
    ), null)
    private constructor(alias: Name, aliased: Table<PostgisSrsSearchRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)

    /**
     * Create an aliased <code>public.postgis_srs_search</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.postgis_srs_search</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.postgis_srs_search</code> table reference
     */
    constructor(): this(DSL.name("postgis_srs_search"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): PostgisSrsSearch = PostgisSrsSearch(DSL.name(alias), this, parameters)
    override fun `as`(alias: Name): PostgisSrsSearch = PostgisSrsSearch(alias, this, parameters)
    override fun `as`(alias: Table<*>): PostgisSrsSearch = PostgisSrsSearch(alias.qualifiedName, this, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: String): PostgisSrsSearch = PostgisSrsSearch(DSL.name(name), null, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PostgisSrsSearch = PostgisSrsSearch(name, null, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PostgisSrsSearch = PostgisSrsSearch(name.qualifiedName, null, parameters)

    /**
     * Call this table-valued function
     */
    fun call(
          bounds: Geometry?
        , authname: String?
    ): PostgisSrsSearch = PostgisSrsSearch(DSL.name("postgis_srs_search"), null, arrayOf(
        DSL.value(bounds, SQLDataType.GEOMETRY),
        DSL.value(authname, SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("'EPSG'::text"), SQLDataType.CLOB)))
    )).let { if (aliased()) it.`as`(unqualifiedName) else it }

    /**
     * Call this table-valued function
     */
    fun call(
          bounds: Field<Geometry?>
        , authname: Field<String?>
    ): PostgisSrsSearch = PostgisSrsSearch(DSL.name("postgis_srs_search"), null, arrayOf(
        bounds,
        authname
    )).let { if (aliased()) it.`as`(unqualifiedName) else it }
}
