/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.tables


import java.time.Instant
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Geometry
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import yayauheny.by.Public
import yayauheny.by.indexes.IDX_RESTROOMS_CITY_ID
import yayauheny.by.indexes.IDX_RESTROOMS_COORDINATES
import yayauheny.by.indexes.IDX_RESTROOMS_IS_DELETED
import yayauheny.by.indexes.IDX_RESTROOMS_STATUS
import yayauheny.by.keys.RESTROOMS_COORDINATES_KEY
import yayauheny.by.keys.RESTROOMS_PKEY
import yayauheny.by.keys.RESTROOMS__RESTROOMS_CITY_ID_FKEY
import yayauheny.by.tables.Cities.CitiesPath
import yayauheny.by.tables.records.RestroomsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Restrooms(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RestroomsRecord>?,
    parentPath: InverseForeignKey<out Record, RestroomsRecord>?,
    aliased: Table<RestroomsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RestroomsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.restrooms</code>
         */
        val RESTROOMS: Restrooms = Restrooms()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RestroomsRecord> = RestroomsRecord::class.java

    /**
     * The column <code>public.restrooms.id</code>.
     */
    val ID: TableField<RestroomsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.restrooms.city_id</code>.
     */
    val CITY_ID: TableField<RestroomsRecord, UUID?> = createField(DSL.name("city_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.restrooms.name</code>.
     */
    val NAME: TableField<RestroomsRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.restrooms.description</code>.
     */
    val DESCRIPTION: TableField<RestroomsRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.restrooms.address</code>.
     */
    val ADDRESS: TableField<RestroomsRecord, String?> = createField(DSL.name("address"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.restrooms.phones</code>.
     */
    val PHONES: TableField<RestroomsRecord, JSONB?> = createField(DSL.name("phones"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.restrooms.work_time</code>.
     */
    val WORK_TIME: TableField<RestroomsRecord, JSONB?> = createField(DSL.name("work_time"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.restrooms.fee_type</code>.
     */
    val FEE_TYPE: TableField<RestroomsRecord, String?> = createField(DSL.name("fee_type"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>public.restrooms.accessibility_type</code>.
     */
    val ACCESSIBILITY_TYPE: TableField<RestroomsRecord, String?> = createField(DSL.name("accessibility_type"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>public.restrooms.coordinates</code>.
     */
    val COORDINATES: TableField<RestroomsRecord, Geometry?> = createField(DSL.name("coordinates"), SQLDataType.GEOMETRY.nullable(false), this, "")

    /**
     * The column <code>public.restrooms.data_source</code>.
     */
    val DATA_SOURCE: TableField<RestroomsRecord, String?> = createField(DSL.name("data_source"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>public.restrooms.status</code>.
     */
    val STATUS: TableField<RestroomsRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>public.restrooms.amenities</code>.
     */
    val AMENITIES: TableField<RestroomsRecord, JSONB?> = createField(DSL.name("amenities"), SQLDataType.JSONB.defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "")

    /**
     * The column <code>public.restrooms.parent_place_name</code>.
     */
    val PARENT_PLACE_NAME: TableField<RestroomsRecord, String?> = createField(DSL.name("parent_place_name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.restrooms.parent_place_type</code>.
     */
    val PARENT_PLACE_TYPE: TableField<RestroomsRecord, String?> = createField(DSL.name("parent_place_type"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column <code>public.restrooms.inherit_parent_schedule</code>.
     */
    val INHERIT_PARENT_SCHEDULE: TableField<RestroomsRecord, Boolean?> = createField(DSL.name("inherit_parent_schedule"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.restrooms.is_deleted</code>.
     */
    val IS_DELETED: TableField<RestroomsRecord, Boolean?> = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.restrooms.created_at</code>.
     */
    val CREATED_AT: TableField<RestroomsRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.INSTANT.nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.INSTANT)), this, "")

    /**
     * The column <code>public.restrooms.updated_at</code>.
     */
    val UPDATED_AT: TableField<RestroomsRecord, Instant?> = createField(DSL.name("updated_at"), SQLDataType.INSTANT.nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.INSTANT)), this, "")

    /**
     * The column <code>public.restrooms.deleted_at</code>.
     */
    val DELETED_AT: TableField<RestroomsRecord, Instant?> = createField(DSL.name("deleted_at"), SQLDataType.INSTANT, this, "")

    private constructor(alias: Name, aliased: Table<RestroomsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RestroomsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RestroomsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.restrooms</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.restrooms</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.restrooms</code> table reference
     */
    constructor(): this(DSL.name("restrooms"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RestroomsRecord>?, parentPath: InverseForeignKey<out Record, RestroomsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, RESTROOMS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class RestroomsPath : Restrooms, Path<RestroomsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RestroomsRecord>?, parentPath: InverseForeignKey<out Record, RestroomsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<RestroomsRecord>): super(alias, aliased)
        override fun `as`(alias: String): RestroomsPath = RestroomsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): RestroomsPath = RestroomsPath(alias, this)
        override fun `as`(alias: Table<*>): RestroomsPath = RestroomsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_RESTROOMS_CITY_ID, IDX_RESTROOMS_COORDINATES, IDX_RESTROOMS_IS_DELETED, IDX_RESTROOMS_STATUS)
    override fun getPrimaryKey(): UniqueKey<RestroomsRecord> = RESTROOMS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<RestroomsRecord>> = listOf(RESTROOMS_COORDINATES_KEY)
    override fun getReferences(): List<ForeignKey<RestroomsRecord, *>> = listOf(RESTROOMS__RESTROOMS_CITY_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.cities</code> table.
     */
    fun cities(): CitiesPath = cities
    val cities: CitiesPath by lazy { CitiesPath(this, RESTROOMS__RESTROOMS_CITY_ID_FKEY, null) }
    override fun `as`(alias: String): Restrooms = Restrooms(DSL.name(alias), this)
    override fun `as`(alias: Name): Restrooms = Restrooms(alias, this)
    override fun `as`(alias: Table<*>): Restrooms = Restrooms(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Restrooms = Restrooms(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Restrooms = Restrooms(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Restrooms = Restrooms(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Restrooms = Restrooms(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Restrooms = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Restrooms = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Restrooms = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Restrooms = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Restrooms = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Restrooms = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Restrooms = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Restrooms = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Restrooms = where(DSL.notExists(select))
}
