/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.tables


import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Geometry
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import yayauheny.by.Public
import yayauheny.by.tables.records.StHexagongridRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StHexagongrid(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, StHexagongridRecord>?,
    parentPath: InverseForeignKey<out Record, StHexagongridRecord>?,
    aliased: Table<StHexagongridRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<StHexagongridRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.function(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.st_hexagongrid</code>
         */
        val ST_HEXAGONGRID: StHexagongrid = StHexagongrid()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<StHexagongridRecord> = StHexagongridRecord::class.java
    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val GEOM: TableField<StHexagongridRecord, Any?> = createField(DSL.name("geom"), DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "")

    /**
     * The column <code>public.st_hexagongrid.i</code>.
     */
    val I: TableField<StHexagongridRecord, Int?> = createField(DSL.name("i"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.st_hexagongrid.j</code>.
     */
    val J: TableField<StHexagongridRecord, Int?> = createField(DSL.name("j"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<StHexagongridRecord>?): this(alias, null, null, null, aliased, arrayOf(
        DSL.value(null, SQLDataType.DOUBLE),
        DSL.value(null, SQLDataType.GEOMETRY)
    ), null)
    private constructor(alias: Name, aliased: Table<StHexagongridRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)

    /**
     * Create an aliased <code>public.st_hexagongrid</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.st_hexagongrid</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.st_hexagongrid</code> table reference
     */
    constructor(): this(DSL.name("st_hexagongrid"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): StHexagongrid = StHexagongrid(DSL.name(alias), this, parameters)
    override fun `as`(alias: Name): StHexagongrid = StHexagongrid(alias, this, parameters)
    override fun `as`(alias: Table<*>): StHexagongrid = StHexagongrid(alias.qualifiedName, this, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: String): StHexagongrid = StHexagongrid(DSL.name(name), null, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: Name): StHexagongrid = StHexagongrid(name, null, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): StHexagongrid = StHexagongrid(name.qualifiedName, null, parameters)

    /**
     * Call this table-valued function
     */
    fun call(
          size: Double?
        , bounds: Geometry?
    ): StHexagongrid = StHexagongrid(DSL.name("st_hexagongrid"), null, arrayOf(
        DSL.value(size, SQLDataType.DOUBLE),
        DSL.value(bounds, SQLDataType.GEOMETRY)
    )).let { if (aliased()) it.`as`(unqualifiedName) else it }

    /**
     * Call this table-valued function
     */
    fun call(
          size: Field<Double?>
        , bounds: Field<Geometry?>
    ): StHexagongrid = StHexagongrid(DSL.name("st_hexagongrid"), null, arrayOf(
        size,
        bounds
    )).let { if (aliased()) it.`as`(unqualifiedName) else it }
}
