version: '3.9'

services:
  postgres:
    platform: linux/amd64
    image: postgis/postgis:17-3.5
    container_name: postgres_tt
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres 
      -c max_connections=100
      -c shared_buffers=128MB
      -c effective_cache_size=384MB
      -c maintenance_work_mem=64MB
      -c work_mem=4MB
      -c random_page_cost=1.1
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c max_wal_size=2GB
      -c min_wal_size=1GB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local