@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.keys


import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.QOM.ForeignKeyRule

import yayauheny.by.tables.Cities
import yayauheny.by.tables.Countries
import yayauheny.by.tables.Restrooms
import yayauheny.by.tables.SpatialRefSys
import yayauheny.by.tables.records.CitiesRecord
import yayauheny.by.tables.records.CountriesRecord
import yayauheny.by.tables.records.RestroomsRecord
import yayauheny.by.tables.records.SpatialRefSysRecord



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val CITIES_COORDINATES_KEY: UniqueKey<CitiesRecord> = Internal.createUniqueKey(Cities.CITIES, DSL.name("cities_coordinates_key"), arrayOf(Cities.CITIES.COORDINATES), true)
val CITIES_PKEY: UniqueKey<CitiesRecord> = Internal.createUniqueKey(Cities.CITIES, DSL.name("cities_pkey"), arrayOf(Cities.CITIES.ID), true)
val CITIES_UNIQUE_COUNTRY_NAME_EN: UniqueKey<CitiesRecord> = Internal.createUniqueKey(Cities.CITIES, DSL.name("cities_unique_country_name_en"), arrayOf(Cities.CITIES.COUNTRY_ID, Cities.CITIES.NAME_EN), true)
val CITIES_UNIQUE_COUNTRY_NAME_RU: UniqueKey<CitiesRecord> = Internal.createUniqueKey(Cities.CITIES, DSL.name("cities_unique_country_name_ru"), arrayOf(Cities.CITIES.COUNTRY_ID, Cities.CITIES.NAME_RU), true)
val COUNTRIES_CODE_KEY: UniqueKey<CountriesRecord> = Internal.createUniqueKey(Countries.COUNTRIES, DSL.name("countries_code_key"), arrayOf(Countries.COUNTRIES.CODE), true)
val COUNTRIES_PKEY: UniqueKey<CountriesRecord> = Internal.createUniqueKey(Countries.COUNTRIES, DSL.name("countries_pkey"), arrayOf(Countries.COUNTRIES.ID), true)
val RESTROOMS_COORDINATES_KEY: UniqueKey<RestroomsRecord> = Internal.createUniqueKey(Restrooms.RESTROOMS, DSL.name("restrooms_coordinates_key"), arrayOf(Restrooms.RESTROOMS.COORDINATES), true)
val RESTROOMS_PKEY: UniqueKey<RestroomsRecord> = Internal.createUniqueKey(Restrooms.RESTROOMS, DSL.name("restrooms_pkey"), arrayOf(Restrooms.RESTROOMS.ID), true)
val SPATIAL_REF_SYS_PKEY: UniqueKey<SpatialRefSysRecord> = Internal.createUniqueKey(SpatialRefSys.SPATIAL_REF_SYS, DSL.name("spatial_ref_sys_pkey"), arrayOf(SpatialRefSys.SPATIAL_REF_SYS.SRID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val CITIES__CITIES_COUNTRY_ID_FKEY: ForeignKey<CitiesRecord, CountriesRecord> = Internal.createForeignKey(Cities.CITIES, DSL.name("cities_country_id_fkey"), arrayOf(Cities.CITIES.COUNTRY_ID), yayauheny.by.keys.COUNTRIES_PKEY, arrayOf(Countries.COUNTRIES.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val RESTROOMS__RESTROOMS_CITY_ID_FKEY: ForeignKey<RestroomsRecord, CitiesRecord> = Internal.createForeignKey(Restrooms.RESTROOMS, DSL.name("restrooms_city_id_fkey"), arrayOf(Restrooms.RESTROOMS.CITY_ID), yayauheny.by.keys.CITIES_PKEY, arrayOf(Cities.CITIES.ID), true, ForeignKeyRule.SET_NULL, ForeignKeyRule.NO_ACTION)
