@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */

package yayauheny.by.indexes

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal

import yayauheny.by.tables.Cities
import yayauheny.by.tables.Countries
import yayauheny.by.tables.Restrooms

// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_CITIES_BOUNDS: Index = Internal.createIndex(DSL.name("idx_cities_bounds"), Cities.CITIES, arrayOf(Cities.CITIES.CITY_BOUNDS), false)
val IDX_CITIES_COORDINATES: Index =
    Internal.createIndex(
        DSL.name("idx_cities_coordinates"),
        Cities.CITIES,
        arrayOf(Cities.CITIES.COORDINATES),
        false
    )
val IDX_CITIES_COUNTRY_ID: Index =
    Internal.createIndex(
        DSL.name("idx_cities_country_id"),
        Cities.CITIES,
        arrayOf(Cities.CITIES.COUNTRY_ID),
        false
    )
val IDX_CITIES_IS_DELETED: Index =
    Internal.createIndex(
        DSL.name("idx_cities_is_deleted"),
        Cities.CITIES,
        arrayOf(Cities.CITIES.IS_DELETED),
        false
    )
val IDX_COUNTRIES_IS_DELETED: Index =
    Internal.createIndex(
        DSL.name("idx_countries_is_deleted"),
        Countries.COUNTRIES,
        arrayOf(Countries.COUNTRIES.IS_DELETED),
        false
    )
val IDX_RESTROOMS_CITY_ID: Index =
    Internal.createIndex(
        DSL.name("idx_restrooms_city_id"),
        Restrooms.RESTROOMS,
        arrayOf(Restrooms.RESTROOMS.CITY_ID),
        false
    )
val IDX_RESTROOMS_COORDINATES: Index =
    Internal.createIndex(
        DSL.name("idx_restrooms_coordinates"),
        Restrooms.RESTROOMS,
        arrayOf(Restrooms.RESTROOMS.COORDINATES),
        false
    )
val IDX_RESTROOMS_IS_DELETED: Index =
    Internal.createIndex(
        DSL.name("idx_restrooms_is_deleted"),
        Restrooms.RESTROOMS,
        arrayOf(Restrooms.RESTROOMS.IS_DELETED),
        false
    )
val IDX_RESTROOMS_STATUS: Index =
    Internal.createIndex(
        DSL.name("idx_restrooms_status"),
        Restrooms.RESTROOMS,
        arrayOf(Restrooms.RESTROOMS.STATUS),
        false
    )
