/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.udt

import org.jooq.Geometry
import org.jooq.Schema
import org.jooq.UDTField
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.UDTImpl

import yayauheny.by.Public
import yayauheny.by.udt.records.GeometryDumpRecord

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GeometryDump : UDTImpl<GeometryDumpRecord>(DSL.name("geometry_dump"), null, null, DSL.comment(""), false) {
    companion object {
        /**
         * The reference instance of <code>public.geometry_dump</code>
         */
        val GEOMETRY_DUMP: GeometryDump = GeometryDump()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<GeometryDumpRecord> = GeometryDumpRecord::class.java

    /**
     * The attribute <code>public.geometry_dump.path</code>.
     */
    val PATH: UDTField<GeometryDumpRecord, Array<Int?>> = UDTImpl.createField(DSL.name("path"), SQLDataType.INTEGER.array(), this, "")

    /**
     * The attribute <code>public.geometry_dump.geom</code>.
     */
    val GEOM: UDTField<GeometryDumpRecord, Geometry> = UDTImpl.createField(DSL.name("geom"), SQLDataType.GEOMETRY, this, "")

    override fun getSchema(): Schema = Public.PUBLIC
}
