/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.tables.records


import org.jooq.impl.TableRecordImpl

import yayauheny.by.tables.GeometryColumns


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GeometryColumnsRecord() : TableRecordImpl<GeometryColumnsRecord>(GeometryColumns.GEOMETRY_COLUMNS) {

    open var fTableCatalog: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var fTableSchema: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var fTableName: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var fGeometryColumn: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var coordDimension: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var srid: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var type: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    /**
     * Create a detached, initialised GeometryColumnsRecord
     */
    constructor(fTableCatalog: String? = null, fTableSchema: String? = null, fTableName: String? = null, fGeometryColumn: String? = null, coordDimension: Int? = null, srid: Int? = null, type: String? = null): this() {
        this.fTableCatalog = fTableCatalog
        this.fTableSchema = fTableSchema
        this.fTableName = fTableName
        this.fGeometryColumn = fGeometryColumn
        this.coordDimension = coordDimension
        this.srid = srid
        this.type = type
        resetTouchedOnNotNull()
    }
}
