/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.tables.records


import org.jooq.impl.TableRecordImpl

import yayauheny.by.tables.PostgisSrsCodes


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class PostgisSrsCodesRecord() : TableRecordImpl<PostgisSrsCodesRecord>(PostgisSrsCodes.POSTGIS_SRS_CODES) {

    open var postgisSrsCodes: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    /**
     * Create a detached, initialised PostgisSrsCodesRecord
     */
    constructor(postgisSrsCodes: String? = null): this() {
        this.postgisSrsCodes = postgisSrsCodes
        resetTouchedOnNotNull()
    }
}
