/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.tables.records


import java.time.Instant
import java.util.UUID

import org.jooq.Geometry
import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

import yayauheny.by.tables.Restrooms


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class RestroomsRecord() : UpdatableRecordImpl<RestroomsRecord>(Restrooms.RESTROOMS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var cityId: UUID?
        set(value): Unit = set(1, value)
        get(): UUID? = get(1) as UUID?

    open var name: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var description: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var address: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var phones: JSONB?
        set(value): Unit = set(5, value)
        get(): JSONB? = get(5) as JSONB?

    open var workTime: JSONB?
        set(value): Unit = set(6, value)
        get(): JSONB? = get(6) as JSONB?

    open var feeType: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var accessibilityType: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var coordinates: Geometry?
        set(value): Unit = set(9, value)
        get(): Geometry? = get(9) as Geometry?

    open var dataSource: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var status: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var amenities: JSONB?
        set(value): Unit = set(12, value)
        get(): JSONB? = get(12) as JSONB?

    open var parentPlaceName: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    open var parentPlaceType: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    open var inheritParentSchedule: Boolean?
        set(value): Unit = set(15, value)
        get(): Boolean? = get(15) as Boolean?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(16, value)
        get(): Boolean? = get(16) as Boolean?

    open var createdAt: Instant?
        set(value): Unit = set(17, value)
        get(): Instant? = get(17) as Instant?

    open var updatedAt: Instant?
        set(value): Unit = set(18, value)
        get(): Instant? = get(18) as Instant?

    open var deletedAt: Instant?
        set(value): Unit = set(19, value)
        get(): Instant? = get(19) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised RestroomsRecord
     */
    constructor(id: UUID? = null, cityId: UUID? = null, name: String? = null, description: String? = null, address: String? = null, phones: JSONB? = null, workTime: JSONB? = null, feeType: String? = null, accessibilityType: String? = null, coordinates: Geometry? = null, dataSource: String? = null, status: String? = null, amenities: JSONB? = null, parentPlaceName: String? = null, parentPlaceType: String? = null, inheritParentSchedule: Boolean? = null, isDeleted: Boolean? = null, createdAt: Instant? = null, updatedAt: Instant? = null, deletedAt: Instant? = null): this() {
        this.id = id
        this.cityId = cityId
        this.name = name
        this.description = description
        this.address = address
        this.phones = phones
        this.workTime = workTime
        this.feeType = feeType
        this.accessibilityType = accessibilityType
        this.coordinates = coordinates
        this.dataSource = dataSource
        this.status = status
        this.amenities = amenities
        this.parentPlaceName = parentPlaceName
        this.parentPlaceType = parentPlaceType
        this.inheritParentSchedule = inheritParentSchedule
        this.isDeleted = isDeleted
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.deletedAt = deletedAt
        resetTouchedOnNotNull()
    }
}
