/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

import yayauheny.by.tables.SpatialRefSys


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class SpatialRefSysRecord() : UpdatableRecordImpl<SpatialRefSysRecord>(SpatialRefSys.SPATIAL_REF_SYS) {

    open var srid: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var authName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var authSrid: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var srtext: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var proj4text: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised SpatialRefSysRecord
     */
    constructor(srid: Int? = null, authName: String? = null, authSrid: Int? = null, srtext: String? = null, proj4text: String? = null): this() {
        this.srid = srid
        this.authName = authName
        this.authSrid = authSrid
        this.srtext = srtext
        this.proj4text = proj4text
        resetTouchedOnNotNull()
    }
}
