/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.tables.records


import org.jooq.impl.TableRecordImpl

import yayauheny.by.tables.StSquaregrid


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StSquaregridRecord() : TableRecordImpl<StSquaregridRecord>(StSquaregrid.ST_SQUAREGRID) {

    open var geom: Any?
        set(value): Unit = set(0, value)
        get(): Any? = get(0) as Any?

    open var i: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var j: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    /**
     * Create a detached, initialised StSquaregridRecord
     */
    constructor(geom: Any? = null, i: Int? = null, j: Int? = null): this() {
        this.geom = geom
        this.i = i
        this.j = j
        resetTouchedOnNotNull()
    }
}
