/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.udt.paths

import org.jooq.Binding
import org.jooq.Comment
import org.jooq.DataType
import org.jooq.Geometry
import org.jooq.Name
import org.jooq.Record
import org.jooq.RecordQualifier
import org.jooq.UDTField
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.UDTPathTableFieldImpl

import yayauheny.by.udt.ValidDetail
import yayauheny.by.udt.records.ValidDetailRecord

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ValidDetailPath<R : Record, T>(
    name: Name,
    type: DataType<T>,
    qualifier: RecordQualifier<R>,
    comment: Comment,
    binding: Binding<*, T>
) : UDTPathTableFieldImpl<R, ValidDetailRecord, T>(
        name,
        type,
        qualifier,
        ValidDetail.VALID_DETAIL,
        comment,
        binding
    ) {
    /**
     * The attribute <code>public.valid_detail.valid</code>.
     */
    val VALID: UDTField<ValidDetailRecord, Boolean> =
        Internal.createUDTPathField(
            DSL.name("valid"),
            SQLDataType.BOOLEAN,
            this,
            "",
            UDTField::class.java as Class<UDTField<ValidDetailRecord, Boolean>>
        )

    /**
     * The attribute <code>public.valid_detail.reason</code>.
     */
    val REASON: UDTField<ValidDetailRecord, String> =
        Internal.createUDTPathField(
            DSL.name("reason"),
            SQLDataType.VARCHAR,
            this,
            "",
            UDTField::class.java as Class<UDTField<ValidDetailRecord, String>>
        )

    /**
     * The attribute <code>public.valid_detail.location</code>.
     */
    val LOCATION: UDTField<ValidDetailRecord, Geometry> =
        Internal.createUDTPathField(
            DSL.name("location"),
            SQLDataType.GEOMETRY,
            this,
            "",
            UDTField::class.java as Class<UDTField<ValidDetailRecord, Geometry>>
        )
}
