/*
 * This file is generated by jOOQ.
 */
package yayauheny.by.udt.records

import org.jooq.Geometry
import org.jooq.impl.UDTRecordImpl

import yayauheny.by.udt.GeometryDump

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GeometryDumpRecord() : UDTRecordImpl<GeometryDumpRecord>(GeometryDump.GEOMETRY_DUMP) {
    open var path: Array<Int?>?
        set(value): Unit = set(0, value)
        get(): Array<Int?>? = get(0) as Array<Int?>?

    open var geom: Geometry?
        set(value): Unit = set(1, value)
        get(): Geometry? = get(1) as Geometry?

    /**
     * Create a detached, initialised GeometryDumpRecord
     */
    constructor(path: Array<Int?>? = null, geom: Geometry? = null) : this() {
        this.path = path
        this.geom = geom
        resetTouchedOnNotNull()
    }
}
